/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   {type: 'autogenerated', dirName: '.'},
  // ],

  // But you can create a sidebar manually

  ProductSidebar: [
    // 'intro',

    // 'About',

    'weekly_wiki',

    {

      
      type: 'category',
      label: 'Arduino',
      items: [
        'Arduino/Arduino_Getting_Started',
      ],
    
    },

    {

      type: 'category',
      label: 'Grove',
      items: [
        'Grove/Grove',
        'Grove/Grove_System',
        'Grove/Grove_A'
      ],
    
    },

    {

      type: 'category',
      label: 'Seeed Studio XIAO',
      items: [
        'SeeedStudio_XIAO/SeeedStudio_XIAO_Getting_Started',
      ],
    
    },

    {

      type: 'category',
      label: 'Raspberry Pi',
      items: [
        'Raspberry_Pi/Raspberry_Pi_Getting_Started',
      ],
    
    },

    {

      type: 'category',
      label: 'reTerminal',
      items: [
        'reTerminal/reTerminal_Getting_Started',
      ],
    
    },

    {

      type: 'category',
      label: 'NVIDIA',
      items: [
        'NVIDIA/NVIDIA_Getting_Started',
      ],
    
    },

    {

      type: 'category',
      label: 'reServer',
      items: [
        'reServer/reServer_Getting_Started',
      ],
    
    },

    'About',
    'License',
    
  ],

  SenseCAPSidebar: 
  
    [
      
      {

        type: 'category',
        label: 'SenseCAP',
        items: [
          'SenseCAP/SenseCAP_Getting_Started',
        ],
      
      },


    ],

  MakerSidebar: 
  
    [
      
      {

        type: 'category',
        label: 'Maker',
        items: [
          'Maker/Maker_Getting_Started',
        ],
      
      },


    ],

};

module.exports = sidebars;
