// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// Jetson landing page sidebar, focused on Jetson products.
// Owns every Edge/NVIDIA_Jetson doc so that browsing any Jetson page keeps
// this sidebar visible (Back to Wiki returns to the main wiki sidebar).
const sidebars = {
  JetsonSidebar: [
    { type: 'ref', id: 'Getting_Started', label: '<-Back to Wiki', className: 'sideboard_calss' },
    { type: 'doc', id: 'Edge/NVIDIA_Jetson/RecomputerPage', label: 'NVIDIA Jetson Page', className: 'sideboard_calss' },
    {
      type: 'link',
      label: 'Devices',
      href: '/NVIDIA_Jetson/?tab=devices',
      className: 'sideboard_calss',
    },
    {
      type: 'category',
      label: 'Carrier Boards',
        customProps: { devicesTab: 0 },
        collapsed: true,
        collapsible: true,
        items: [
          'Edge/NVIDIA_Jetson/Carrier_Boards/J101/reComputer_J1010_J101_Flash_Jetpack',
          'Edge/NVIDIA_Jetson/Carrier_Boards/J202/reComputer_J2021_J202_Flash_Jetpack',
          {
            type: 'category',
            label: 'J401 Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/J401/reComputer_J4012_Flash_Jetpack',
              'Edge/NVIDIA_Jetson/Carrier_Boards/J401/J401_carrierboard_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'J401-Mini Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/Mini_J401/reComputer_Mini_J4012_Flash_Jetpack',
              'Edge/NVIDIA_Jetson/Carrier_Boards/Mini_J401/J401_Mini_carrierboard_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'reServer J501 Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/J501/reServer_Industrial_J501_Getting_Started',
              'Edge/NVIDIA_Jetson/Carrier_Boards/J501/Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'J501-Mini Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/J501_Mini/Robotics_J501_Mini_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'J401-Robotics Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/Robotics_J401/Robotics_J401_carrierboard_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'J601-Robotics Carrier Board',
            items: [
              {
                type: 'doc',
                id: 'Edge/NVIDIA_Jetson/Carrier_Boards/Robotics_J601/reComputer_Robotics_J601_Getting_Started',
                label: 'Getting Started',
              },
              'Edge/NVIDIA_Jetson/Carrier_Boards/Robotics_J601/Robotics_J601_carrierboard_Hardware_Interfaces_Usage',
            ],
          },
          'Edge/NVIDIA_Jetson/Carrier_Boards/A203v2/reComputer_A203_Flash_System',
          'Edge/NVIDIA_Jetson/Carrier_Boards/A205/reComputer_A205_Flash_System',
          'Edge/NVIDIA_Jetson/Carrier_Boards/A603/A603_Flash_JetPack',
          'Edge/NVIDIA_Jetson/Carrier_Boards/A607/A607_Flash_JetPack',
          'Edge/NVIDIA_Jetson/Carrier_Boards/A608/A608_Flash_JetPack',
        ],
      },
      {
        type: 'category',
        label: 'reComputer Jetson',
        customProps: { devicesTab: 4 },
        collapsed: true,
        collapsible: true,
        items: [
          {
            type: 'category',
            label: 'reComputer J10',
            link: { type: 'doc', id: 'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_Jetson_Series_Introduction' },
            items: [
              {
                type: 'category',
                label: 'reComputer J1010',
                items: [
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/reComputer_J1010_with_Jetson_getting_start',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/J101_Enable_SD_Card',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/J1010_Boot_From_SD_Card',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/reComputer_Jetson_GPIO',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/reComputer_Jetson_Memory_Expansion',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/reComputer_Jetson_Series_Hardware_Layout',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/reComputer_Jetson_Series_Initiation',
                ],
              },
              {
                type: 'category',
                label: 'reComputer J1020',
                items: [
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1020v2/reComputer_J1020v2_with_Jetson_getting_start',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1020v2/reComputer_J1020_A206_Flash_JetPack',
                ],
              },
            ],
          },
          {
            type: 'category',
            label: 'reComputer J20',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J20/reComputer_J20_with_Jetson_getting_start',
            ],
          },
          {
            type: 'category',
            label: 'reComputer J30/40',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J30_40/reComputer_J30_40_with_Jetson_getting_start',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J30_40/reComputer_Jetson_with_Infineon_Wi-Fi_Module',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Industrial',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Industrial/reComputer_Industrial_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Industrial/reComputer_Industrial_J20_Hardware_Interfaces_Usage',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Industrial/reComputer_Industrial_J40_J30_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Mini',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Mini/reComputer_Mini_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Mini/reComputer_Mini_Hardware_Interfaces_Usage',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Mini/reComputer_Mini_J501_WiFi_Module_Installation',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Rugged J40',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Rugged_J40/reComputer_Rugged_J40_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Rugged_J40/reComputer_Rugged_J401_hardware_and_interface_usage',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Rugged_J40/reComputer_Rugged_J401_for_Industrial_Vision',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Robotics J40',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Robotics_J40/reComputer_Robotics_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Robotics_J40/reComputer_Robotics_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Robotics J50',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Robotics_J50/reComputer_Robotics_J501_Getting_Started',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Classic J50',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Classic_J50/Seeed_AGX_Orin_Dev_Kit_Getting_Started',
            ],
          },
          {
            type: 'category',
            label: 'reComputer J401B',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J401B/recomputer_j401b_getting_start',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J401B/recomputer_j401b_interfaces_usage',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Super',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/reComputer_Super_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/reComputer_Super_Hardware_Interfaces_Usage',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/reComputer_Super_vs_Classic_Next-Gen_AI_Performance_in_Edge_Inferencing',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/Replace_the_Thermal_Conductive_Paste_for_reComputer',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/reComputer_Antenna_Installation',
            ],
          },
        ],
      },
      {
        type: 'category',
        label: 'reServer Jetson',
        customProps: { devicesTab: 7 },
        collapsed: true,
        collapsible: true,
        items: [
          {
            type: 'category',
            label: 'reServer Industrial J30/40',
            items: [
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_Industrial_J30_J40/reServer_Industrial_Getting_Started',
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_Industrial_J30_J40/reServer_Industrial_Hardware_Interface_Usage',
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_Industrial_J30_J40/reServer_Industrial_POE_Camera_Usage',
            ],
          },
          {
            type: 'category',
            label: 'reServer J2032',
            items: [
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_J2032/reServer_J2032_Flash_Jetpack',
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_J2032/reServer_J2032_Getting_Started',
            ],
          },
        ],
      },
{
      type: 'category',
      label: 'Accessories',
      collapsed: true,
      collapsible: true,
      items: [
        'Edge/NVIDIA_Jetson/Other_Devices/RTL8822CE_Wireless_Module_for_Jetson',
        'Edge/NVIDIA_Jetson/Other_Devices/RTL8852BE_Wireless_Module_for_Jetson',
        'Edge/NVIDIA_Jetson/Other_Devices/RM520N_Module_for_Jetson',
        'Edge/NVIDIA_Jetson/Other_Devices/EM12-G_GNSS_Module_for_reComputer_Robotics_J3011',
        'Edge/NVIDIA_Jetson/FAQs/How_to_use_Camera_IMX219',
        'Edge/NVIDIA_Jetson/FAQs/Use_IMX477_Camera_with_A603',
        'Edge/NVIDIA_Jetson/FAQs/Use_Arducam_OV9281_Camera_with_A603',
        'Edge/NVIDIA_Jetson/FAQs/Solution_for_the_Compatibility_Issue_between_reComputer_and_VEYE_Camera',
        'Edge/NVIDIA_Jetson/FAQs/JetPack72_AX210_AX200_WiFi_Setup_Guide',
        'Edge/NVIDIA_Jetson/Application/Computer_Vision/ZED_X_GMSL_Cameras_on_reComputer_Robotics',
      ],
    },
    {
      type: 'category',
      label: 'Other Devices',
      customProps: { devicesTab: 8 },
      collapsed: true,
      collapsible: true,
      items: [
        'Edge/NVIDIA_Jetson/Other_Devices/reBot_Arm_Jetson_Bundle',
        'Edge/NVIDIA_Jetson/Other_Devices/How_to_Update_Orin_Nano_Developer_Kit_to_Super_Kit',
        'Edge/NVIDIA_Jetson/Other_Devices/Jetson_AGX_Orin_32GB_H01_Flash_Jetpack',
        'Edge/NVIDIA_Jetson/Other_Devices/Jetson_Xavier_AGX_H01_Driver_Installation',
        'Edge/NVIDIA_Jetson/Other_Devices/Jetson-Mate',
        'Edge/NVIDIA_Jetson/Other_Devices/Mini_AI_Computer_T906',
        'Edge/NVIDIA_Jetson/Other_Devices/reComputer_A203E_Flash_System',
        'Edge/NVIDIA_Jetson/Other_Devices/reComputer_A205E_Flash_System',
        'Edge/NVIDIA_Jetson/Other_Devices/reComputer_Jetson_Series_GPIO_Grove',
      ],
    },
    {
      type: 'category',
      label: 'Learn',
      className: 'robotics-section-title',
      collapsed: true,
      collapsible: true,
      items: [
      'Edge/NVIDIA_Jetson/Jetson_Product_Selection_Guide',
      'Edge/NVIDIA_Jetson/Flash_Jetpack',
      'Edge/NVIDIA_Jetson/Jetson_Debug_Guide',
      { type: 'link', label: 'reComputer Jetson for Beginners', href: 'https://sensecraft.seeed.cc/ai-lab/en/tutorials/j/introduction' },
      { type: 'link', label: 'OSHW-Jetson-Series', href: 'https://github.com/Seeed-Studio/OSHW-Jetson-Series' },
      { type: 'link', label: 'Linux for Tegra', href: 'https://github.com/Seeed-Studio/Linux_for_Tegra' },
      {
        type: 'category',
        label: 'JetPack 7.2',
        collapsed: true,
        collapsible: true,
        items: [
          'Edge/NVIDIA_Jetson/JetPack_7_2/JetPack_7_2_Overview',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Flashing_OTA/Flash_and_OTA_JetPack_7_2',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Migration/JetPack_6_to_7_Migration_Playbook',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Platform/JetPack_7_2_Unified_Platform_ISO_SBSA',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Platform/JetPack_7_2_MAXN_SUPER_and_MIG',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Drivers/JetPack_7_2_Camera_and_Multimedia_Compatibility',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Optimization/JetPack_7_2_Memory_Optimization',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Optimization/JetPack_7_2_Memory_Optimization_Deep_Dive',
          'Edge/NVIDIA_Jetson/JetPack_7_2/AI_Inference/JetPack_7_2_DeepStream',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Application/Deploy_Full_Weight_GR00T_N1_7_TensorRT_on_AGX_Orin',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Deploy_TensorRT_Edge-LLM_on_Jetpack7.2',
        ],
      },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      className: 'jetson-applications-title',
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Seeed Jetson DevelopTool',
          collapsed: true,
          collapsible: true,
          items: [
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_Overview',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_Supported_Devices',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_Installation',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_Connect_Device',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_Flash_Firmware',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_Device_Management',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_App_Market',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_Skills',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_Remote_Development',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/Jetson_DevelopTool_FAQ',
          ],
        },
        { type: 'link', label: 'jetson-examples', href: 'https://sensecraft.seeed.cc/ai-lab/en/models' },
      ],
    },
    {
      type: 'category',
      label: 'FAQs',
      className: 'jetson-applications-title',
      items: [
        'Edge/NVIDIA_Jetson/FAQs/jetson_FAQ',
        {
          type: 'category',
          label: 'System & Flashing',
          collapsed: true,
          collapsible: true,
          items: [
            'Edge/NVIDIA_Jetson/FAQs/Create_Backup_and_Restore_on_reComputer',
            'Edge/NVIDIA_Jetson/FAQs/Migrate_Home_Data_from_Jetson_Orin_Nano_Developer_Kit_to_reComputer',
            'Edge/NVIDIA_Jetson/FAQs/Deploy_OTA_ON_reComputer',
            'Edge/NVIDIA_Jetson/FAQs/Flash_JetPack_with_WSL2',
            'Edge/NVIDIA_Jetson/FAQs/Headless_Setup_and_Recovery_for_A603',
            'Edge/NVIDIA_Jetson/FAQs/Jetson_Initrd_Flash_Fails_with_ZFS_Host',
            'Edge/NVIDIA_Jetson/FAQs/Weston_EGL_NOT_INITIALIZED_on_Jetson_Cold_Boot',
          ],
        },
        {
          type: 'category',
          label: 'BSP & Development',
          collapsed: true,
          collapsible: true,
          items: [
            'Edge/NVIDIA_Jetson/FAQs/Make_DIY_BSP_for_Jetson',
            'Edge/NVIDIA_Jetson/FAQs/Make_DIY_BSP_from_Orin_Nano_DevKit_to_reComputer_Classic_And_Super',
            'Edge/NVIDIA_Jetson/FAQs/How_to_Build_and_Flash_BSP_Source_for_Jetson_Thor',
            'Edge/NVIDIA_Jetson/FAQs/How_to_Establish_the_Ethercat_on_Jetson',
          ],
        },
        {
          type: 'category',
          label: 'Knowledge',
          collapsed: true,
          collapsible: true,
          items: [
            'Edge/NVIDIA_Jetson/FAQs/Differences_of_L4T_Between_Seeed_and_NVIDIA',
            'Edge/NVIDIA_Jetson/FAQs/Overview_of_the_Relationship_Between_JetPack_and_Jetson',
          ],
        },
      ],
    },
    {
      type: 'link',
      label: 'Applications',
      href: '/NVIDIA_Jetson/?tab=community',
      className: 'sideboard_calss',
    },
    {
      type: 'category',
      label: 'Computer Vision',
          customProps: { communityCategory: 'cv' },
          items: [
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/Build_a_Four_Camera_Fisheye_Surround_View_Demo_on_Jetson_AGX_Thor',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/Streaming_Vision_Agent_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/industrial_vision_monitoring_on_industrial',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/YOLOv26_Dual_USB_Camera_Image_Processing_System_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/Deploy_NVBLOX_ON_Jetson_AGX_Orin',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/Deploy_Depth_Anything_V3_ON_Jetson_AGX_Orin',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/Multi-GMSL_Cameras_for_Real-Time_Object_Detection_and_3D_Reconstruction_on_Jetson_AGX_Orin',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/YOLOv11_With_Depth_Camera_For_Distance_Measurement',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/deploy_frigate_on_jetson',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/AI-NVR_with_Jetson',
          ],
        },
        {
          type: 'category',
          label: 'Generative AI',
          customProps: { communityCategory: 'gen' },
          items: [
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Finetune_LLM_by_Llama_Factory_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Whisper_on_Jetson_for_Real_Time_Speech_to_Text',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Local_RAG_based_on_Jetson_with_LlamaIndex',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Deploy_JoyAI_VL_Interaction_on_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Local_OpenClaw(Clawdbot)_on_reComputer_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Deploy_Live_VLM_WebUI_on_reComputer_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Deploy_Ollama_and_AnythingLLM_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Quickly_Deploy_DeepSeek_on_reComputer_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Deploy_DeepSeek_on_reComputer_Jetson_with_MLC',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/GPT_OSS_Running_Live_on_reComputer_Jetson',
          ],
        },
        {
          type: 'category',
          label: 'Developer Tools',
          customProps: { communityCategory: 'devtools' },
          items: [
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Build_and_Flash_Yocto_for_reComputer_Super',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Develop_reComputer_Jetson_using_Clawdbot',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Gapi-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/alwaysAI-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Cochl.Sense-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/CVEDIA-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/DeciAI-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/HardHat',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Jetson-AI-developer-tools',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/jetson-docker-getting-started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Lumeo-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/reComputer_Jetson_Series_Resource',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/NVStreamer_Getting_Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Roboflow-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Install_torch_on_reComputer',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/vnc_for_reComputer',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Implement_Ethercat_communication_on_reComputer',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Distributed_llama_cpp_RPC_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Deploy_TensorRT_Edge-LLM_on_Jetpack6.2',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Deploy_TensorRT_Model_Connect_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Jetson_SPI_Getting_Start',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Flash_PREEMPT_RT_Kernel_on_reComputer_Jetson_JetPack_6_2_1',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Deploy_PREEMPT_RT_Kernel_with_Prebuilt_DEB_Package_on_reComputer_Jetson',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/Rapid_Prototyping_on_Jetson_with_NVIDIA_Skills',
          ],
        },
        {
          type: 'category',
          label: 'Multimodal AI',
          customProps: { communityCategory: 'multimodal' },
          items: [
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/Local_Voice_LLM_for_Reachy_Mini',
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/Speech_vlm',
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/use_vlm_guard_warehouse',
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/Local_Chatbot_reComputer',
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/llm_interface_control_jetson',
          ],
        },
        {
          type: 'category',
          label: 'Physical AI',
          customProps: { communityCategory: 'physical' },
          items: [
            'Edge/NVIDIA_Jetson/Application/Physical_AI/Microduck_RL_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/Getting_Started_with_Jetson_Claw_on_Orin_Nano_NX_8GB',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/Fine_tune_GR00T_N1.5_for_LeRobot_SO_Arm_and_Deploy_on_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/Fine_tune_GR00T_N1.6_for_LeRobot_SO_Arm_and_Deploy_on_AGX_Orin',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/Fine_tune_GR00T_N1.7_for_reBot_Arm_and_Deploy_on_Robotics_J601',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/J501_Mini_StarAI_Viola_Fruit_Sorting',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/Control_SoArm_by_OpenClaw_on_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/Control_reBot_Arm_by_NemoClaw_on_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/Voice_Control_reBot_Arm_B601_by_Nvidia_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/reBot_Arm_B601_DM_GraspNet_Visual_Grasping',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/Control_Motor_by_Voice_LLM_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/Multiple_Reachy_Mini_Robots_with_a_Fleet_Dance_Console_on_Jetson',
          ],
        },
        {
          type: 'category',
          label: 'Managed Services',
          customProps: { communityCategory: 'managed' },
          items: [
            'Edge/NVIDIA_Jetson/Application/Managed_Services/Allxon-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Managed_Services/neqto_engine_for_linux_recomputer',
            'Edge/NVIDIA_Jetson/Application/Managed_Services/Scailable-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Managed_Services/Update-Jetson-Linux-OTA-Using-Allxon',
          ],
        },
  ],
};

module.exports = sidebars;
