// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// Jetson landing page sidebar, focused on Jetson products.
// Owns every Edge/NVIDIA_Jetson doc so that browsing any Jetson page keeps
// this sidebar visible (Back to Wiki returns to the main wiki sidebar).
const sidebars = {
  JetsonSidebar: [
    { type: 'ref', id: 'es_Getting_Started', label: '<-Volver al Wiki', className: 'sideboard_calss' },
    { type: 'doc', id: 'Edge/NVIDIA_Jetson/es_RecomputerPage', label: 'Página de NVIDIA Jetson', className: 'sideboard_calss' },
    {
      type: 'link',
      label: 'Dispositivos',
      href: '/es/NVIDIA_Jetson/?tab=devices',
      className: 'sideboard_calss',
    },
    {
      type: 'category',
      label: 'Placas Portadoras',
        collapsed: true,
        collapsible: true,
        items: [
          'Edge/NVIDIA_Jetson/Carrier_Boards/J101/es_reComputer_J1010_J101_Flash_Jetpack',
          'Edge/NVIDIA_Jetson/Carrier_Boards/J202/es_reComputer_J2021_J202_Flash_Jetpack',
          {
            type: 'category',
            label: 'J401 Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/J401/es_reComputer_J4012_Flash_Jetpack',
              'Edge/NVIDIA_Jetson/Carrier_Boards/J401/es_J401_carrierboard_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'J401-Mini Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/Mini_J401/es_reComputer_Mini_J4012_Flash_Jetpack',
              'Edge/NVIDIA_Jetson/Carrier_Boards/Mini_J401/es_J401_Mini_carrierboard_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'reServer J501 Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/J501/es_reServer_Industrial_J501_Getting_Started',
              'Edge/NVIDIA_Jetson/Carrier_Boards/J501/es_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'J501-Mini Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/J501_Mini/es_Robotics_J501_Mini_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'J401-Robotics Carrier Board',
            items: [
              'Edge/NVIDIA_Jetson/Carrier_Boards/Robotics_J401/es_Robotics_J401_carrierboard_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'J601-Robotics Carrier Board',
            items: [
              {
                type: 'doc',
                id: 'Edge/NVIDIA_Jetson/Carrier_Boards/Robotics_J601/es_reComputer_Robotics_J601_Getting_Started',
                label: 'Comenzando',
              },
              'Edge/NVIDIA_Jetson/Carrier_Boards/Robotics_J601/es_Robotics_J601_carrierboard_Hardware_Interfaces_Usage',
            ],
          },
          'Edge/NVIDIA_Jetson/Carrier_Boards/A203v2/es_reComputer_A203_Flash_System',
          'Edge/NVIDIA_Jetson/Carrier_Boards/A205/es_reComputer_A205_Flash_System',
          'Edge/NVIDIA_Jetson/Carrier_Boards/A603/es_A603_Flash_JetPack',
          'Edge/NVIDIA_Jetson/Carrier_Boards/A607/es_A607_Flash_JetPack',
          'Edge/NVIDIA_Jetson/Carrier_Boards/A608/es_A608_Flash_JetPack',
        ],
      },
      {
        type: 'category',
        label: 'reComputer Jetson',
        collapsed: true,
        collapsible: true,
        link: { type: 'doc', id: 'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/es_reComputer_Intro' },
        items: [
          {
            type: 'category',
            label: 'reComputer J10',
            link: { type: 'doc', id: 'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/es_reComputer_Jetson_Series_Introduction' },
            items: [
              {
                type: 'category',
                label: 'reComputer J1010',
                items: [
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/es_reComputer_J1010_with_Jetson_getting_start',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/es_J101_Enable_SD_Card',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/es_J1010_Boot_From_SD_Card',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/es_reComputer_Jetson_GPIO',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/es_reComputer_Jetson_Memory_Expansion',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/es_reComputer_Jetson_Series_Hardware_Layout',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1010/es_reComputer_Jetson_Series_Initiation',
                ],
              },
              {
                type: 'category',
                label: 'reComputer J1020',
                items: [
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1020v2/es_reComputer_J1020v2_with_Jetson_getting_start',
                  'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J10/reComputer_J1020v2/es_reComputer_J1020_A206_Flash_JetPack',
                ],
              },
            ],
          },
          {
            type: 'category',
            label: 'reComputer J20',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J20/es_reComputer_J20_with_Jetson_getting_start',
            ],
          },
          {
            type: 'category',
            label: 'reComputer J30/40',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J30_40/es_reComputer_J30_40_with_Jetson_getting_start',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J30_40/es_reComputer_Jetson_with_Infineon_Wi-Fi_Module',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Industrial',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Industrial/es_reComputer_Industrial_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Industrial/es_reComputer_Industrial_J20_Hardware_Interfaces_Usage',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Industrial/es_reComputer_Industrial_J40_J30_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Mini',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Mini/es_reComputer_Mini_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Mini/es_reComputer_Mini_Hardware_Interfaces_Usage',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Mini/es_reComputer_Mini_J501_WiFi_Module_Installation',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Rugged J40',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Rugged_J40/es_reComputer_Rugged_J40_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Rugged_J40/es_reComputer_Rugged_J401_hardware_and_interface_usage',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Rugged_J40/es_reComputer_Rugged_J401_for_Industrial_Vision',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Robotics J40',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Robotics_J40/es_reComputer_Robotics_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Robotics_J40/es_reComputer_Robotics_Hardware_Interfaces_Usage',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Robotics J50',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Robotics_J50/es_reComputer_Robotics_J501_Getting_Started',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Classic J50',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Classic_J50/es_Seeed_AGX_Orin_Dev_Kit_Getting_Started',
            ],
          },
          {
            type: 'category',
            label: 'reComputer J401B',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J401B/es_recomputer_j401b_getting_start',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_J401B/es_recomputer_j401b_interfaces_usage',
            ],
          },
          {
            type: 'category',
            label: 'reComputer Super',
            items: [
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/es_reComputer_Super_Getting_Started',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/es_reComputer_Super_Hardware_Interfaces_Usage',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/es_reComputer_Super_vs_Classic_Next-Gen_AI_Performance_in_Edge_Inferencing',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/es_Replace_the_Thermal_Conductive_Paste_for_reComputer',
              'Edge/NVIDIA_Jetson/reComputer_Jetson_Series/reComputer_Super/es_reComputer_Antenna_Installation',
            ],
          },
        ],
      },
      {
        type: 'category',
        label: 'reServer Jetson',
        collapsed: true,
        collapsible: true,
        items: [
          {
            type: 'category',
            label: 'reServer Industrial J30/40',
            items: [
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_Industrial_J30_J40/es_reServer_Industrial_Getting_Started',
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_Industrial_J30_J40/es_reServer_Industrial_Hardware_Interface_Usage',
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_Industrial_J30_J40/es_reServer_Industrial_POE_Camera_Usage',
            ],
          },
          {
            type: 'category',
            label: 'reServer J2032',
            items: [
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_J2032/es_reServer_J2032_Flash_Jetpack',
              'Edge/NVIDIA_Jetson/reServer_Jetson_Series/reServer_J2032/es_reServer_J2032_Getting_Started',
            ],
          },
        ],
      },
{
      type: 'category',
      label: 'Accesorios',
      collapsed: true,
      collapsible: true,
      items: [
        'Edge/NVIDIA_Jetson/Other_Devices/es_RTL8822CE_Wireless_Module_for_Jetson',
        'Edge/NVIDIA_Jetson/Other_Devices/es_RTL8852BE_Wireless_Module_for_Jetson',
        'Edge/NVIDIA_Jetson/Other_Devices/es_RM520N_Module_for_Jetson',
        'Edge/NVIDIA_Jetson/Other_Devices/es_EM12-G_GNSS_Module_for_reComputer_Robotics_J3011',
      ],
    },
    {
      type: 'category',
      label: 'Otros Dispositivos',
      collapsed: true,
      collapsible: true,
      items: [
        'Edge/NVIDIA_Jetson/Other_Devices/es_reBot_Arm_Jetson_Bundle',
        'Edge/NVIDIA_Jetson/Other_Devices/es_How_to_Update_Orin_Nano_Developer_Kit_to_Super_Kit',
        'Edge/NVIDIA_Jetson/Other_Devices/es_Jetson_AGX_Orin_32GB_H01_Flash_Jetpack',
        'Edge/NVIDIA_Jetson/Other_Devices/es_Jetson_Xavier_AGX_H01_Driver_Installation',
        'Edge/NVIDIA_Jetson/Other_Devices/es_Jetson-Mate',
        'Edge/NVIDIA_Jetson/Other_Devices/es_Mini_AI_Computer_T906',
        'Edge/NVIDIA_Jetson/Other_Devices/es_reComputer_A203E_Flash_System',
        'Edge/NVIDIA_Jetson/Other_Devices/es_reComputer_A205E_Flash_System',
        'Edge/NVIDIA_Jetson/Other_Devices/es_reComputer_Jetson_Series_GPIO_Grove',
      ],
    },
    {
      type: 'category',
      label: 'Aprender',
      className: 'robotics-section-title',
      collapsed: true,
      collapsible: true,
      items: [
      'Edge/NVIDIA_Jetson/es_Jetson_Product_Selection_Guide',
      'Edge/NVIDIA_Jetson/es_Flash_Jetpack',
      'Edge/NVIDIA_Jetson/es_Jetson_Debug_Guide',
      { type: 'link', label: 'reComputer Jetson for Beginners', href: 'https://sensecraft.seeed.cc/ai-lab/en/tutorials/j/introduction' },
      { type: 'link', label: 'OSHW-Jetson-Series', href: 'https://github.com/Seeed-Studio/OSHW-Jetson-Series' },
      {
        type: 'category',
        label: 'JetPack 7.2',
        collapsed: true,
        collapsible: true,
        items: [
          'Edge/NVIDIA_Jetson/JetPack_7_2/es_JetPack_7_2_Overview',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Flashing_OTA/es_Flash_and_OTA_JetPack_7_2',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Migration/es_JetPack_6_to_7_Migration_Playbook',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Platform/es_JetPack_7_2_Unified_Platform_ISO_SBSA',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Platform/es_JetPack_7_2_MAXN_SUPER_and_MIG',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Drivers/es_JetPack_7_2_Camera_and_Multimedia_Compatibility',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Optimization/es_JetPack_7_2_Memory_Optimization',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Optimization/es_JetPack_7_2_Memory_Optimization_Deep_Dive',
          'Edge/NVIDIA_Jetson/JetPack_7_2/AI_Inference/es_JetPack_7_2_DeepStream',
          'Edge/NVIDIA_Jetson/JetPack_7_2/Application/es_Deploy_Full_Weight_GR00T_N1_7_TensorRT_on_AGX_Orin',
          'Edge/NVIDIA_Jetson/JetPack_7_2/es_Deploy_TensorRT_Edge-LLM_on_Jetpack7.2',
        ],
      },
      ],
    },
    {
      type: 'category',
      label: 'Herramientas',
      className: 'jetson-applications-title',
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Seeed Jetson DevelopTool',
          collapsed: true,
          collapsible: true,
          items: [
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_Overview',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_Supported_Devices',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_Installation',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_Connect_Device',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_Flash_Firmware',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_Device_Management',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_App_Market',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_Skills',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_Remote_Development',
            'Edge/NVIDIA_Jetson/Jetson_DevelopTool/es_Jetson_DevelopTool_FAQ',
          ],
        },
        { type: 'link', label: 'jetson-examples', href: 'https://sensecraft.seeed.cc/ai-lab/en/models' },
        { type: 'link', label: 'Linux for Tegra', href: 'https://github.com/Seeed-Studio/Linux_for_Tegra' },
      ],
    },
    {
      type: 'category',
      label: 'Preguntas Frecuentes',
      className: 'jetson-applications-title',
      items: [
        'Edge/NVIDIA_Jetson/FAQs/es_jetson_FAQ',
        'Edge/NVIDIA_Jetson/FAQs/es_Create_Backup_and_Restore_on_reComputer',
        'Edge/NVIDIA_Jetson/FAQs/es_Migrate_Home_Data_from_Jetson_Orin_Nano_Developer_Kit_to_reComputer',
        'Edge/NVIDIA_Jetson/FAQs/es_Deploy_OTA_ON_reComputer',
        'Edge/NVIDIA_Jetson/FAQs/es_Headless_Setup_and_Recovery_for_A603',
        'Edge/NVIDIA_Jetson/FAQs/es_Solution_for_the_Compatibility_Issue_between_reComputer_and_VEYE_Camera',
        'Edge/NVIDIA_Jetson/FAQs/es_How_to_use_Camera_IMX219',
        'Edge/NVIDIA_Jetson/FAQs/es_Use_IMX477_Camera_with_A603',
        'Edge/NVIDIA_Jetson/FAQs/es_Use_Arducam_OV9281_Camera_with_A603',
        'Edge/NVIDIA_Jetson/FAQs/es_Differences_of_L4T_Between_Seeed_and_NVIDIA',
        'Edge/NVIDIA_Jetson/FAQs/es_Overview_of_the_Relationship_Between_JetPack_and_Jetson',
        'Edge/NVIDIA_Jetson/FAQs/es_How_to_Establish_the_Ethercat_on_Jetson',
        'Edge/NVIDIA_Jetson/FAQs/es_Make_DIY_BSP_for_Jetson',
        'Edge/NVIDIA_Jetson/FAQs/es_Make_DIY_BSP_from_Orin_Nano_DevKit_to_reComputer_Classic_And_Super',
        'Edge/NVIDIA_Jetson/FAQs/es_How_to_Build_and_Flash_BSP_Source_for_Jetson_Thor',
        'Edge/NVIDIA_Jetson/FAQs/es_Weston_EGL_NOT_INITIALIZED_on_Jetson_Cold_Boot',
        'Edge/NVIDIA_Jetson/FAQs/es_Flash_JetPack_with_WSL2',
        'Edge/NVIDIA_Jetson/FAQs/es_Jetson_Initrd_Flash_Fails_with_ZFS_Host',
      ],
    },
    {
      type: 'link',
      label: 'Aplicaciones',
      href: '/es/NVIDIA_Jetson/?tab=community',
      className: 'sideboard_calss',
    },
    {
      type: 'category',
      label: 'Visión por Computadora',
          items: [
            { type: 'link', label: 'Ver proyectos', href: '/es/NVIDIA_Jetson/?tab=community&category=cv' },
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_ZED_X_GMSL_Cameras_on_reComputer_Robotics',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_Build_a_Four_Camera_Fisheye_Surround_View_Demo_on_Jetson_AGX_Thor',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_Streaming_Vision_Agent_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_industrial_vision_monitoring_on_industrial',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_YOLOv26_Dual_USB_Camera_Image_Processing_System_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_Deploy_NVBLOX_ON_Jetson_AGX_Orin',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_Deploy_Depth_Anything_V3_ON_Jetson_AGX_Orin',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_Multi-GMSL_Cameras_for_Real-Time_Object_Detection_and_3D_Reconstruction_on_Jetson_AGX_Orin',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_YOLOv11_With_Depth_Camera_For_Distance_Measurement',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_deploy_frigate_on_jetson',
            'Edge/NVIDIA_Jetson/Application/Computer_Vision/es_AI-NVR_with_Jetson',
          ],
        },
        {
          type: 'category',
          label: 'IA Generativa',
          items: [
            { type: 'link', label: 'Ver proyectos', href: '/es/NVIDIA_Jetson/?tab=community&category=gen' },
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Finetune_LLM_by_Llama_Factory_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Whisper_on_Jetson_for_Real_Time_Speech_to_Text',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Local_RAG_based_on_Jetson_with_LlamaIndex',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Deploy_JoyAI_VL_Interaction_on_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Local_OpenClaw(Clawdbot)_on_reComputer_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Deploy_Live_VLM_WebUI_on_reComputer_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Deploy_Ollama_and_AnythingLLM_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Quickly_Deploy_DeepSeek_on_reComputer_Jetson',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Deploy_DeepSeek_on_reComputer_Jetson_with_MLC',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_GPT_OSS_Running_Live_on_reComputer_Jetson',
          ],
        },
        {
          type: 'category',
          label: 'Herramientas de Desarrollador',
          items: [
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Build_and_Flash_Yocto_for_reComputer_Super',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Develop_reComputer_Jetson_using_Clawdbot',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Gapi-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_alwaysAI-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Cochl.Sense-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_CVEDIA-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_DeciAI-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_HardHat',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Jetson-AI-developer-tools',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_jetson-docker-getting-started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Lumeo-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_reComputer_Jetson_Series_Resource',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_NVStreamer_Getting_Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Roboflow-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Install_torch_on_reComputer',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_vnc_for_reComputer',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Implement_Ethercat_communication_on_reComputer',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Distributed_llama_cpp_RPC_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Deploy_TensorRT_Edge-LLM_on_Jetpack6.2',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Deploy_TensorRT_Model_Connect_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Jetson_SPI_Getting_Start',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Flash_PREEMPT_RT_Kernel_on_reComputer_Jetson_JetPack_6_2_1',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Deploy_PREEMPT_RT_Kernel_with_Prebuilt_DEB_Package_on_reComputer_Jetson',
            'Edge/NVIDIA_Jetson/Application/Developer_Tools/es_Rapid_Prototyping_on_Jetson_with_NVIDIA_Skills',
          ],
        },
        {
          type: 'category',
          label: 'IA Multimodal',
          items: [
            { type: 'link', label: 'Ver proyectos', href: '/es/NVIDIA_Jetson/?tab=community&category=multimodal' },
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/es_Local_Voice_LLM_for_Reachy_Mini',
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/es_Speech_vlm',
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/es_use_vlm_guard_warehouse',
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/es_Local_Chatbot_reComputer',
            'Edge/NVIDIA_Jetson/Application/Multimodal_AI/es_llm_interface_control_jetson',
          ],
        },
        {
          type: 'category',
          label: 'IA Encarnada',
          items: [
            { type: 'link', label: 'Ver proyectos', href: '/es/NVIDIA_Jetson/?tab=community&category=physical' },
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_Microduck_RL_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_Getting_Started_with_Jetson_Claw_on_Orin_Nano_NX_8GB',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_Fine_tune_GR00T_N1.5_for_LeRobot_SO_Arm_and_Deploy_on_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_Fine_tune_GR00T_N1.6_for_LeRobot_SO_Arm_and_Deploy_on_AGX_Orin',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_Fine_tune_GR00T_N1.7_for_reBot_Arm_and_Deploy_on_Robotics_J601',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_J501_Mini_StarAI_Viola_Fruit_Sorting',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_Control_SoArm_by_OpenClaw_on_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_Control_reBot_Arm_by_NemoClaw_on_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_Voice_Control_reBot_Arm_B601_by_Nvidia_Jetson_Thor',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_reBot_Arm_B601_DM_GraspNet_Visual_Grasping',
            'Edge/NVIDIA_Jetson/Application/Generative_AI/es_Control_Motor_by_Voice_LLM_on_Jetson',
            'Edge/NVIDIA_Jetson/Application/Physical_AI/es_Multiple_Reachy_Mini_Robots_with_a_Fleet_Dance_Console_on_Jetson',
          ],
        },
        {
          type: 'category',
          label: 'Servicios Administrados',
          items: [
            { type: 'link', label: 'Ver proyectos', href: '/es/NVIDIA_Jetson/?tab=community&category=managed' },
            'Edge/NVIDIA_Jetson/Application/Managed_Services/es_Allxon-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Managed_Services/es_neqto_engine_for_linux_recomputer',
            'Edge/NVIDIA_Jetson/Application/Managed_Services/es_Scailable-Jetson-Getting-Started',
            'Edge/NVIDIA_Jetson/Application/Managed_Services/es_Update-Jetson-Linux-OTA-Using-Allxon',
          ],
        },
  ],
};

module.exports = sidebars;
