// Auto-generated by generate-jetson-config.js
// DO NOT EDIT MANUALLY - Run "npm run generate-jetson-config" to regenerate
// Generated at: 2026-02-12T03:11:49.490Z

export const communityList_cv = [
  {
    "name": "AI NVR with Jetson Orin",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/ai-nvr/vst.png",
    "URL": "https://wiki.seeedstudio.com/ai_nvr_with_jetson",
    "category": [],
    "lastUpdated": "08/12/2024",
    "author": "Youjiang"
  },
  {
    "name": "DashCamNet with Jetson Xavier NX Multicamera",
    "img": "https://developer.nvidia.com/sites/default/files/akamai/metropolis-and-iva-tao-toolkit-sw-stack-update-diagram-1875240-r7.jpg",
    "URL": "https://wiki.seeedstudio.com/DashCamNet-with-Jetson-Xavier-NX-Multicamera",
    "category": [],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "Deploy Depth Anything V3 on Jetson AGX Orin",
    "img": "https://files.seeedstudio.com/wiki/deploy_depth_anything_v3/da3_head.webp",
    "URL": "https://wiki.seeedstudio.com/deploy_depth_anything_v3_jetson_agx_orin",
    "category": [],
    "lastUpdated": "2026-01-09",
    "author": "Zibo"
  },
  {
    "name": "Deploy Frigate On Jetson",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Deploy_Frigate_On_Jetson/3.png",
    "URL": "https://wiki.seeedstudio.com/deploy_frigate_on_jetson",
    "category": [],
    "lastUpdated": "08/29/2024",
    "author": "kourosh"
  },
  {
    "name": "Deploy NVBlox with Orbbec Camera on Jetson AGX Orin",
    "img": "https://files.seeedstudio.com/wiki/other/page-nvblox.jpg",
    "URL": "https://wiki.seeedstudio.com/deploy_nvblox_jetson_agx_orin",
    "category": [],
    "lastUpdated": "2026-01-20",
    "author": "Dayu"
  },
  {
    "name": "Efficient Multi-Task Vision Inference Engine Deployment on Jetson",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/v_engine/video_demo_preview.gif",
    "URL": "https://wiki.seeedstudio.com/deploy_visual_perception_engine_recomputer",
    "category": [],
    "lastUpdated": "2025-10-13",
    "author": "Zibo"
  },
  {
    "name": "How to train and deploy YOLOv8 on reComputer",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/reComputer_J4012.png",
    "URL": "https://wiki.seeedstudio.com/How_to_Train_and_Deploy_YOLOv8_on_reComputer",
    "category": [],
    "lastUpdated": "12/6/2023",
    "author": "Youjiang"
  },
  {
    "name": "MaskCam",
    "img": "https://files.seeedstudio.com/wiki/Jetson-Nano-MaskCam/tu12.png",
    "URL": "https://wiki.seeedstudio.com/Jetson-Nano-MaskCam",
    "category": [],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "Multi-GMSL Cameras for Real-Time Object Detection and 3D Reconstruction on Jetson AGX Orin",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/J501/yolo1.webp",
    "URL": "https://wiki.seeedstudio.com/multiple_cameras_with_jetson",
    "category": [],
    "lastUpdated": "06/30/2025",
    "author": "Zibo"
  },
  {
    "name": "Jetson Community Projects",
    "img": "https://files.seeedstudio.com/wiki/recomputer-Jetson-20-1-H1/reprojects.jpg",
    "URL": "https://wiki.seeedstudio.com/reComputer_Jetson_Series_Projects",
    "category": [],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "reComputer for Jetson Tutorials and Exercise",
    "img": "https://files.seeedstudio.com/wiki/recomputerzhongwen/rexuexi.png",
    "URL": "https://wiki.seeedstudio.com/reComputer_Jetson_Series_Tutorials_Exercise",
    "category": [],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "Security Xray Scan Knife Detection",
    "img": "https://files.seeedstudio.com/wiki/SecurityCheck/Security_Scan_23.png",
    "URL": "https://wiki.seeedstudio.com/Security_Scan",
    "category": [],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "Traffic Management DeepStream SDK",
    "img": "https://files.seeedstudio.com/wiki/DeepStream/demo-optimized.gif",
    "URL": "https://wiki.seeedstudio.com/Traffic-Management-DeepStream-SDK",
    "category": [],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "YOLOv11 With Depth Camera on Jetson Orin For Distance Measurement",
    "img": "https://files.seeedstudio.com/wiki/Yolo11/connection.webp",
    "URL": "https://wiki.seeedstudio.com/yolov11_with_depth_camera",
    "category": [],
    "lastUpdated": "07/04/2025",
    "author": "Zibo"
  },
  {
    "name": "YOLOv26 Dual GMS Camera Image Processing System on Jetson",
    "img": "https://files.seeedstudio.com/wiki/yolov26_on_jetson/local.png",
    "URL": "https://wiki.seeedstudio.com/ai_roboticsyolov26_dual_camera_system",
    "category": [],
    "lastUpdated": "02/10/2026",
    "author": "Lorraine"
  },
  {
    "name": "Getting started with Yolov5 and roboflow",
    "img": "https://files.seeedstudio.com/wiki/YOLOV5/YOLOv5_banner.jpg",
    "URL": "https://wiki.seeedstudio.com/YOLOv5-Object-Detection-Jetson",
    "category": [
      "Data Label",
      "AI model train",
      "AI model deploy",
      "Roboflow"
    ],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "Deploy YOLOv8 with TensorRT and DeepStream SDK",
    "img": "https://files.seeedstudio.com/wiki/YOLOV8/car.gif",
    "URL": "https://wiki.seeedstudio.com/YOLOv8-DeepStream-TRT-Jetson",
    "category": [
      "Data Label",
      "AI model train",
      "AI model deploy",
      "Yolov8"
    ],
    "lastUpdated": "04/21/2023",
    "author": "Lakshantha"
  },
  {
    "name": "Deploy YOLOv8 with TensorRT",
    "img": "https://files.seeedstudio.com/wiki/YOLOV8-TRT/8.gif",
    "URL": "https://wiki.seeedstudio.com/YOLOv8-TRT-Jetson",
    "category": [
      "Data Label",
      "AI model train",
      "AI model deploy",
      "Yolov8"
    ],
    "lastUpdated": "07/17/2023",
    "author": "Lakshantha"
  },
  {
    "name": "Train and deploy a custom classification model with YOLOv8",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/reComputer_J4012.png",
    "URL": "https://wiki.seeedstudio.com/train_and_deploy_a_custom_classification_model_with_yolov8",
    "category": [],
    "lastUpdated": "06/11/2024",
    "author": "Bruno"
  }
]

export const communityList_gen = [
  {
    "name": "Control Motor by Voice LLM on Jetson",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/voice_control/hardware_connect.webp",
    "URL": "https://wiki.seeedstudio.com/control_motor_by_voice_llm_on_jetson",
    "category": [],
    "lastUpdated": "08/19/2025",
    "author": "Youjiang"
  },
  {
    "name": "Deploy DeepSeek on reComputer Jetson with MLC",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/deepseek/mlc/deploy_deepseek.webp",
    "URL": "https://wiki.seeedstudio.com/deploy_deepseek_on_jetson_with_mlc",
    "category": [],
    "lastUpdated": "02/13/2025",
    "author": "Youjiang"
  },
  {
    "name": "Deploy Dia on reComputer Jetson",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/deepseek/mlc/deploy_deepseek.webp",
    "URL": "https://wiki.seeedstudio.com/deploy_dia_on_jetson",
    "category": [],
    "lastUpdated": "05/16/2025",
    "author": "Youjiang"
  },
  {
    "name": "Deploy Live VLM WebUI on reComputer Jetson",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/gpt_oss/gptoss-running-live.webp",
    "URL": "https://wiki.seeedstudio.com/deploy_live_vlm_webui_on_jetson",
    "category": [],
    "lastUpdated": "12/26/2025",
    "author": "Youjiang"
  },
  {
    "name": "Local AI Assistant",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/local-ai-assistant/ai-assistant.png",
    "URL": "https://wiki.seeedstudio.com/local_ai_ssistant",
    "category": [],
    "lastUpdated": "07/30/2024",
    "author": "Youjiang"
  },
  {
    "name": "Local Voice Chatbot",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Local_Voice_Chatbot/workflow.png",
    "URL": "https://wiki.seeedstudio.com/Local_Voice_Chatbot",
    "category": [],
    "lastUpdated": "01/14/2024",
    "author": "Youjiang"
  },
  {
    "name": "Finetune with Llama-Factory",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/Llama-Factory/run.gif",
    "URL": "https://wiki.seeedstudio.com/Finetune_LLM_on_Jetson",
    "category": [],
    "lastUpdated": "07/03/2024",
    "author": "Youjiang"
  },
  {
    "name": "Generative AI with reComputer-Jetson®",
    "img": "https://files.seeedstudio.com/wiki/reComputer/deploy-genai-on-jetson.png",
    "URL": "https://wiki.seeedstudio.com/Generative_AI_Intro",
    "category": [],
    "lastUpdated": "08/06/2024",
    "author": "Youjiang"
  },
  {
    "name": "GPT-OSS Running Live on reComputer Jetson!",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/gpt_oss/gptoss-running-live.webp",
    "URL": "https://wiki.seeedstudio.com/deploy_gptoss_on_jetson",
    "category": [],
    "lastUpdated": "08/14/2025",
    "author": "Youjiang"
  },
  {
    "name": "Format Output with Langchain",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Format_LLM_Opt/ai_assistant.png",
    "URL": "https://wiki.seeedstudio.com/How_to_Format_the_Output_of_LLM_Using_Langchain_on_Jetson",
    "category": [],
    "lastUpdated": "4/1/2024",
    "author": "Youjiang"
  },
  {
    "name": "Text2Image with Stable Diffusion",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/reComputer_J4012.png",
    "URL": "https://wiki.seeedstudio.com/How_to_run_local_llm_text_to_image_on_reComputer",
    "category": [],
    "lastUpdated": "04/01/2024",
    "author": "Bruno"
  },
  {
    "name": "How to Run VLM on reComputer",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/vlm/vlmgif.gif",
    "URL": "https://wiki.seeedstudio.com/run_vlm_on_recomputer",
    "category": [],
    "lastUpdated": "7/24/2024",
    "author": "ZhuYaoHui"
  },
  {
    "name": "How to Run Zero-Shot Detection on reComputer",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/zero_shot_detection/fig1.gif",
    "URL": "https://wiki.seeedstudio.com/run_zero_shot_detection_on_recomputer",
    "category": [],
    "lastUpdated": "7/24/2024",
    "author": "ZhuYaoHui"
  },
  {
    "name": "RAG with LlamaIndex",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/RAG-MLC-Jetson.gif",
    "URL": "https://wiki.seeedstudio.com/Local_RAG_based_on_Jetson_with_LlamaIndex",
    "category": [],
    "lastUpdated": "05/15/2024",
    "author": "Jiahao"
  },
  {
    "name": "Faster Inference with MLC",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/MLC_LLM.gif",
    "URL": "https://wiki.seeedstudio.com/Quantized_Llama2_7B_with_MLC_LLM_on_Jetson",
    "category": [],
    "lastUpdated": "04/1/2024",
    "author": "Jiahao"
  },
  {
    "name": "Quickly Deploy DeepSeek on reComputer Jetson",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/deepseek/deepseek.webp",
    "URL": "https://wiki.seeedstudio.com/deploy_deepseek_on_jetson",
    "category": [],
    "lastUpdated": "02/08/2025",
    "author": "Youjiang"
  },
  {
    "name": "Real Time Subtitle Recoder",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/recoder.gif",
    "URL": "https://wiki.seeedstudio.com/Real Time Subtitle Recoder on Nvidia Jetson",
    "category": [],
    "lastUpdated": "02/23/2024",
    "author": "Jiahao"
  },
  {
    "name": "Speech2Text with Whisper",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/Real-Time-Whisper.gif",
    "URL": "https://wiki.seeedstudio.com/Whisper_on_Jetson_for_Real_Time_Speech_to_Text",
    "category": [],
    "lastUpdated": "03/14/2024",
    "author": "Jiahao"
  }
]

export const communityList_robot = []

export const developerToolsList = [
  {
    "name": "Getting Started with alwaysAI",
    "img": "https://files.seeedstudio.com/wiki/alwaysAI/pics/thumb-5.gif",
    "URL": "https://wiki.seeedstudio.com/alwaysAI-Jetson-Getting-Started",
    "category": [
      "Data Label"
    ],
    "lastUpdated": "1/16/2023",
    "author": "jianjing Huang"
  },
  {
    "name": "Getting Started with Cochl.Sense",
    "img": "https://files.seeedstudio.com/wiki/Cochl.Sense/1.gif",
    "URL": "https://wiki.seeedstudio.com/Cochl.Sense-Jetson-Getting-Started",
    "category": [
      "AI model deploy"
    ],
    "lastUpdated": "03/27/2023",
    "author": "Lakshantha"
  },
  {
    "name": "Getting Started with CVEDIA-RT",
    "img": "https://files.seeedstudio.com/wiki/CVEDIA/thumb.gif",
    "URL": "https://wiki.seeedstudio.com/CVEDIA-Jetson-Getting-Started",
    "category": [
      "AI model deploy"
    ],
    "lastUpdated": "03/10/2023",
    "author": "Lakshantha"
  },
  {
    "name": "Getting Started with Deci",
    "img": "https://files.seeedstudio.com/wiki/DeciAI/Deci-thumb.jpg",
    "URL": "https://wiki.seeedstudio.com/DeciAI-Getting-Started",
    "category": [
      "AI model optimize"
    ],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "Distributed llama.cpp on reComputer Jetson (RPC Mode)",
    "img": "https://files.seeedstudio.com/wiki/recomputer_robotic_j501/hardware_overview.png.jpg",
    "URL": "https://wiki.seeedstudio.com/ai_robotics_distributed_llama_cpp_rpc_jetson",
    "category": [],
    "lastUpdated": "2026-01-09",
    "author": "Lorraine"
  },
  {
    "name": "Getting Started with Gapi",
    "img": "https://genainerds.com/assets/img/GapiGIF.gif",
    "URL": "https://wiki.seeedstudio.com/gapi_getting_started-with_jetson",
    "category": [
      "AI model optimize"
    ],
    "lastUpdated": "09/20/2024",
    "author": "Youjiang"
  },
  {
    "name": "Getting Started with Edge Impulse",
    "img": "https://files.seeedstudio.com/wiki/2.23jetsonedge/jetsonedge.png",
    "URL": "https://wiki.seeedstudio.com/HardHat",
    "category": [
      "Data Label",
      "AI model train",
      "AI model deploy"
    ],
    "lastUpdated": "01/04/2023",
    "author": "Bill"
  },
  {
    "name": "Implement Ethercat Communication on reComputer",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/robotics_j401/recomputer-robotics_2.webp",
    "URL": "https://wiki.seeedstudio.com/recomputer_ethercat_communication",
    "category": [],
    "lastUpdated": "2025-09-05",
    "author": "Zibo"
  },
  {
    "name": "Install Pytorch for reComputer Jetson",
    "img": "https://files.seeedstudio.com/wiki/Yolo11/connection.webp",
    "URL": "https://wiki.seeedstudio.com/install_torch_on_recomputer",
    "category": [],
    "lastUpdated": "07/25/2025",
    "author": "Zibo"
  },
  {
    "name": "Jetson AI Developer Tools",
    "img": "https://files.seeedstudio.com/wiki/recomputerzhongwen/cvedia-logo.jpg",
    "URL": "https://wiki.seeedstudio.com/Jetson-AI-developer-tools",
    "category": [],
    "lastUpdated": "05/11/2023",
    "author": "Lakshantha"
  },
  {
    "name": "Getting Started with Docker",
    "img": "https://files.seeedstudio.com/wiki/jetson-docker/1.jpeg",
    "URL": "https://wiki.seeedstudio.com/jetson-docker-getting-started",
    "category": [],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "Getting Started with Lumeo",
    "img": "https://files.seeedstudio.com/wiki/Lumeo/thumb.gif",
    "URL": "https://wiki.seeedstudio.com/Lumeo-Jetson-Getting-Started",
    "category": [
      "AI model deploy"
    ],
    "lastUpdated": "03/10/2023",
    "author": "Lakshantha"
  },
  {
    "name": "No code Edge AI Tool",
    "img": "https://files.seeedstudio.com/wiki/node-red/step.png",
    "URL": "https://wiki.seeedstudio.com/No-code-Edge-AI-Tool",
    "category": [],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "Getting Started with NVStreamer",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/recomputerj4012.jpg",
    "URL": "https://wiki.seeedstudio.com/getting_started_with_nvstreamer",
    "category": [],
    "lastUpdated": "7/24/2024",
    "author": "ZhuYaoHui"
  },
  {
    "name": "Jetson Resource",
    "img": "https://files.seeedstudio.com/wiki/recomputerzhongwen/rewendang.png",
    "URL": "https://wiki.seeedstudio.com/reComputer_Jetson_Series_Resource",
    "category": [],
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": "Getting Started with Roboflow",
    "img": "https://files.seeedstudio.com/wiki/Roboflow-inference/9.gif",
    "URL": "https://wiki.seeedstudio.com/Roboflow-Jetson-Getting-Started",
    "category": [
      "Data Label",
      "AI model train",
      "AI model deploy",
      "Roboflow"
    ],
    "lastUpdated": "10/26/2023",
    "author": "Lakshantha"
  },
  {
    "name": "Using VNC on reComputer Jetson",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/recomputerj4012.jpg",
    "URL": "https://wiki.seeedstudio.com/vnc_for_recomputer",
    "category": [
      "AI model deploy"
    ],
    "lastUpdated": "9/30/2024",
    "author": "YaoHui Zhu"
  }
]

export const multimodalList = [
  {
    "name": "Local LLM Agent on Jetson for Safe Hardware Interface Control",
    "img": "https://www.seeedstudio.com/blog/wp-content/uploads/2024/03/image-1030x616.png",
    "URL": "https://wiki.seeedstudio.com/llm_interface_control_jetson",
    "category": [],
    "lastUpdated": "01/29/2025",
    "author": "kourosh"
  },
  {
    "name": "Chatbot on Jetson",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Multimodal_ai/local_voice_chatbot/terminal_ollama.gif",
    "URL": "https://wiki.seeedstudio.com/local_chatbot_recomputer",
    "category": [],
    "lastUpdated": "01/29/2025",
    "author": "kourosh"
  },
  {
    "name": "Deploy local voice LLM on reComputer Mini for Reachy Mini!",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/reachy_mini/world_frame.webp",
    "URL": "https://wiki.seeedstudio.com/local_voice_llm_on_recomputer_jetson_for_reachy_mini",
    "category": [],
    "lastUpdated": "01/06/2026",
    "author": "youjiang"
  },
  {
    "name": "Run VLM with speech interaction",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Multimodal_ai/audio_vlm/vlmgif.gif",
    "URL": "https://wiki.seeedstudio.com/speech_vlm",
    "category": [],
    "lastUpdated": "08/23/2024",
    "author": "YaoHui Zhu"
  },
  {
    "name": "Use Llava to guard your warehouse",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Industrial/reComputer-Industrial-J4012.webp",
    "URL": "https://wiki.seeedstudio.com/vlm",
    "category": [],
    "lastUpdated": "10/10/2025",
    "author": "Jiahao Li"
  }
]

export const physicalAIList = [
  {
    "name": "Fine-tune Isaac GR00T N1.5 for LeRobot SO-101 Arm and Deploy on Jetson Thor",
    "img": "https://files.seeedstudio.com/wiki/other/cover1.png",
    "URL": "https://wiki.seeedstudio.com/fine_tune_gr00t_n1.5_for_lerobot_so_arm_and_deploy_on_jetson_thor_bk",
    "category": [],
    "lastUpdated": "2025-9-11",
    "author": "AI&Robotics Group"
  },
  {
    "name": "Fine-tune Isaac GR00T N1.6 for LeRobot SO-101 Arm and Deploy on AGX Orin",
    "img": "https://files.seeedstudio.com/wiki/other/cover1.png",
    "URL": "https://wiki.seeedstudio.com/fine_tune_gr00t_n1.6_for_lerobot_so_arm_and_deploy_on_agx_orin",
    "category": [],
    "lastUpdated": "2026-1-6",
    "author": "Dayu"
  },
  {
    "name": "Fruit Sorting with J501 Mini and StarAI Viola Arm",
    "img": "https://files.seeedstudio.com/wiki/other/j501mini-startai-front.png",
    "URL": "https://wiki.seeedstudio.com/j501_mini_starai_viola_fruit_sorting",
    "category": [],
    "lastUpdated": "2026-2-2",
    "author": "Dayu"
  },
  {
    "name": "Chatbot on Jetson",
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Multimodal_ai/local_voice_chatbot/terminal_ollama.gif",
    "URL": "https://wiki.seeedstudio.com/local_chatbot_recomputer_bk",
    "category": [],
    "lastUpdated": "01/29/2025",
    "author": "kourosh"
  },
  {
    "name": "Deploy local voice LLM on reComputer Mini for Reachy Mini!",
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/reachy_mini/world_frame.webp",
    "URL": "https://wiki.seeedstudio.com/local_voice_llm_on_recomputer_jetson_for_reachy_mini_bk",
    "category": [],
    "lastUpdated": "01/06/2026",
    "author": "youjiang"
  }
]

export const managedServicesList = [
  {
    "name": "Getting Started with Allxon",
    "img": "https://www.allxon.com/hs-fs/hubfs/Allxon_%E6%8F%92%E7%95%AB_20210512-+NVIDIA.png?width=1125&height=845&name=Allxon_%E6%8F%92%E7%95%AB_20210512-+NVIDIA.png",
    "URL": "https://wiki.seeedstudio.com/Allxon-Jetson-Getting-Started",
    "category": [
      "Remote Manage"
    ],
    "lastUpdated": "1/13/2023",
    "author": "jianjing Huang"
  },
  {
    "name": "Getting started of NEQTO Engine for Linux on reComputer J30",
    "img": "https://files.seeedstudio.com/wiki/wiki-ranger/Contributions/neqto_engine_for_linux_recomputer/header-img_2x.png",
    "URL": "https://wiki.seeedstudio.com/neqto_engine_for_linux_recomputer",
    "category": [],
    "lastUpdated": "03/14/2024",
    "author": "Kazuhiro Ozuchi"
  },
  {
    "name": "Getting Started with Scailable",
    "img": "https://files.seeedstudio.com/wiki/Scailable/wiki-thumb-4.gif",
    "URL": "https://wiki.seeedstudio.com/Scailable-Jetson-Getting-Started",
    "category": [
      "AI model deploy"
    ],
    "lastUpdated": "03/10/2023",
    "author": "Lakshantha"
  },
  {
    "name": "OTA Update NVIDIA Jetson Using Allxon",
    "img": "https://files.seeedstudio.com/wiki/Allxon/JetPack-OTA/thumb.png",
    "URL": "https://wiki.seeedstudio.com/Update-Jetson-Linux-OTA-Using-Allxon",
    "category": [],
    "lastUpdated": "1/13/2023",
    "author": "jianjing Huang"
  }
]
