// Auto-generated by generate-jetson-config.js
// DO NOT EDIT MANUALLY - Run "node scripts/generate-jetson-config.js" to regenerate
// Generated at: 2026-06-08T07:59:41.571Z

export const communityList_cv = [
  {
    "name": {
      "en": "AI NVR with Jetson Orin",
      "zh": "基于 Jetson Orin 的 AI NVR",
      "ja": "Jetson OrinによるAI NVR",
      "es": "NVR con IA con Jetson Orin",
      "pt": "NVR de IA com Jetson Orin"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/ai-nvr/vst.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/ai_nvr_with_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/ai_nvr_with_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/ai_nvr_with_jetson",
      "es": "https://wiki.seeedstudio.com/es/ai_nvr_with_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/ai_nvr_with_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "08/12/2024",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "DashCamNet with Jetson Xavier NX Multicamera",
      "zh": "使用 Jetson Xavier NX 多摄像头的 DashCamNet",
      "ja": "DashCamNet with Jetson Xavier NX Multicamera",
      "es": "DashCamNet with Jetson Xavier NX Multicamera",
      "pt": "DashCamNet com Jetson Xavier NX Multicâmera"
    },
    "img": "https://developer.nvidia.com/sites/default/files/akamai/metropolis-and-iva-tao-toolkit-sw-stack-update-diagram-1875240-r7.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/DashCamNet-with-Jetson-Xavier-NX-Multicamera",
      "zh": "https://wiki.seeedstudio.com/cn/DashCamNet-with-Jetson-Xavier-NX-Multicamera",
      "ja": "https://wiki.seeedstudio.com/ja/DashCamNet-with-Jetson-Xavier-NX-Multicamera",
      "es": "https://wiki.seeedstudio.com/es/DashCamNet-with-Jetson-Xavier-NX-Multicamera",
      "pt": "https://wiki.seeedstudio.com/pt-br/DashCamNet-with-Jetson-Xavier-NX-Multicamera"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "Deploy Depth Anything V3 on Jetson AGX Orin",
      "zh": "在 Jetson AGX Orin 上部署 Depth Anything V3",
      "ja": "Jetson AGX Orin上でDepth Anything V3をデプロイ",
      "es": "Desplegar Depth Anything V3 en Jetson AGX Orin",
      "pt": "Implantar Depth Anything V3 no Jetson AGX Orin"
    },
    "img": "https://files.seeedstudio.com/wiki/deploy_depth_anything_v3/da3_head.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/deploy_depth_anything_v3_jetson_agx_orin",
      "zh": "https://wiki.seeedstudio.com/cn/deploy_depth_anything_v3_jetson_agx_orin",
      "ja": "https://wiki.seeedstudio.com/ja/deploy_depth_anything_v3_jetson_agx_orin",
      "es": "https://wiki.seeedstudio.com/es/deploy_depth_anything_v3_jetson_agx_orin",
      "pt": "https://wiki.seeedstudio.com/pt-br/deploy_depth_anything_v3_jetson_agx_orin"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "2026-01-09T00:00:00.000Z",
    "author": "Zibo"
  },
  {
    "name": {
      "en": "Deploy Frigate On Jetson",
      "zh": "在 Jetson 上部署 Frigate",
      "ja": "Jetson上にFrigateをデプロイする",
      "es": "Desplegar Frigate en Jetson",
      "pt": "Implantar Frigate no Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Deploy_Frigate_On_Jetson/3.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/deploy_frigate_on_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/deploy_frigate_on_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/deploy_frigate_on_jetson",
      "es": "https://wiki.seeedstudio.com/es/deploy_frigate_on_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/deploy_frigate_on_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "08/29/2024",
    "author": "kourosh"
  },
  {
    "name": {
      "en": "Deploy NVBlox with Orbbec Camera on Jetson AGX Orin",
      "zh": "在 Jetson AGX Orin 上使用 Orbbec 相机部署 NVBlox",
      "ja": "Jetson AGX Orin 上で Orbbec カメラとともに NVBlox をデプロイする",
      "es": "Desplegar NVBlox con cámara Orbbec en Jetson AGX Orin",
      "pt": "Implantar NVBlox com Câmera Orbbec no Jetson AGX Orin"
    },
    "img": "https://files.seeedstudio.com/wiki/other/page-nvblox.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/deploy_nvblox_jetson_agx_orin",
      "zh": "https://wiki.seeedstudio.com/cn/deploy_nvblox_jetson_agx_orin",
      "ja": "https://wiki.seeedstudio.com/ja/deploy_nvblox_jetson_agx_orin",
      "es": "https://wiki.seeedstudio.com/es/deploy_nvblox_jetson_agx_orin",
      "pt": "https://wiki.seeedstudio.com/pt-br/deploy_nvblox_jetson_agx_orin"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "2026-01-20T00:00:00.000Z",
    "author": "Dayu"
  },
  {
    "name": {
      "en": "Efficient Multi-Task Vision Inference Engine Deployment on Jetson",
      "zh": "在 Jetson 上部署高效多任务视觉推理引擎",
      "ja": "Jetsonでの効率的なマルチタスクビジョン推論エンジンの展開",
      "es": "Despliegue de Motor de Inferencia de Visión Multi-Tarea Eficiente en Jetson",
      "pt": "Implantação Eficiente de Motor de Inferência de Visão Multitarefa no Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/v_engine/video_demo_preview.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/deploy_visual_perception_engine_recomputer",
      "zh": "https://wiki.seeedstudio.com/cn/deploy_visual_perception_engine_recomputer",
      "ja": "https://wiki.seeedstudio.com/ja/deploy_visual_perception_engine_recomputer",
      "es": "https://wiki.seeedstudio.com/es/deploy_visual_perception_engine_recomputer",
      "pt": "https://wiki.seeedstudio.com/pt-br/deploy_visual_perception_engine_recomputer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "2025-10-13T00:00:00.000Z",
    "author": "Zibo"
  },
  {
    "name": {
      "en": "How to train and deploy YOLOv8 on reComputer",
      "zh": "如何在 reComputer 上训练和部署 YOLOv8",
      "ja": "reComputerでYOLOv8をトレーニングしてデプロイする方法",
      "es": "Cómo entrenar y desplegar YOLOv8 en reComputer",
      "pt": "Como treinar e implantar YOLOv8 no reComputer"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/reComputer_J4012.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/How_to_Train_and_Deploy_YOLOv8_on_reComputer",
      "zh": "https://wiki.seeedstudio.com/cn/How_to_Train_and_Deploy_YOLOv8_on_reComputer",
      "ja": "https://wiki.seeedstudio.com/ja/How_to_Train_and_Deploy_YOLOv8_on_reComputer",
      "es": "https://wiki.seeedstudio.com/es/How_to_Train_and_Deploy_YOLOv8_on_reComputer",
      "pt": "https://wiki.seeedstudio.com/pt-br/How_to_Train_and_Deploy_YOLOv8_on_reComputer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "12/6/2023",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "MaskCam",
      "zh": "MaskCam",
      "ja": "MaskCam",
      "es": "MaskCam",
      "pt": "MaskCam"
    },
    "img": "https://files.seeedstudio.com/wiki/Jetson-Nano-MaskCam/tu12.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Jetson-Nano-MaskCam",
      "zh": "https://wiki.seeedstudio.com/cn/Jetson-Nano-MaskCam",
      "ja": "https://wiki.seeedstudio.com/ja/Jetson-Nano-MaskCam",
      "es": "https://wiki.seeedstudio.com/es/Jetson-Nano-MaskCam",
      "pt": "https://wiki.seeedstudio.com/pt-br/Jetson-Nano-MaskCam"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "Multi-GMSL Cameras for Real-Time Object Detection and 3D Reconstruction on Jetson AGX Orin",
      "zh": "基于Jetson AGX Orin的多GMSL摄像头实时目标检测和3D重建",
      "ja": "Jetson AGX Orin 上でのマルチ GMSL カメラによるリアルタイム物体検出と 3D 再構成",
      "es": "Múltiples Cámaras GMSL para Detección de Objetos en Tiempo Real y Reconstrucción 3D en Jetson AGX Orin",
      "pt": "Múltiplas Câmeras GMSL para Detecção de Objetos em Tempo Real e Reconstrução 3D no Jetson AGX Orin"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/J501/yolo1.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/multiple_cameras_with_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/multiple_cameras_with_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/multiple_cameras_with_jetson",
      "es": "https://wiki.seeedstudio.com/es/multiple_cameras_with_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/multiple_cameras_with_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "06/30/2025",
    "author": "Zibo"
  },
  {
    "name": {
      "en": "Jetson Community Projects",
      "zh": "Jetson 社区项目",
      "ja": "Jetsonコミュニティプロジェクト",
      "es": "Proyectos de la Comunidad Jetson",
      "pt": "Projetos da Comunidade Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/recomputer-Jetson-20-1-H1/reprojects.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/reComputer_Jetson_Series_Projects",
      "zh": "https://wiki.seeedstudio.com/cn/reComputer_Jetson_Series_Projects",
      "ja": "https://wiki.seeedstudio.com/ja/reComputer_Jetson_Series_Projects",
      "es": "https://wiki.seeedstudio.com/es/reComputer_Jetson_Series_Projects",
      "pt": "https://wiki.seeedstudio.com/pt-br/reComputer_Jetson_Series_Projects"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "reComputer for Jetson Tutorials and Exercise",
      "zh": "reComputer for Jetson 教程和练习",
      "ja": "reComputer for Jetson チュートリアルと演習",
      "es": "Tutoriales y Ejercicios de reComputer para Jetson",
      "pt": "Tutoriais e Exercícios reComputer para Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/recomputerzhongwen/rexuexi.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/reComputer_Jetson_Series_Tutorials_Exercise",
      "zh": "https://wiki.seeedstudio.com/cn/reComputer_Jetson_Series_Tutorials_Exercise",
      "ja": "https://wiki.seeedstudio.com/ja/reComputer_Jetson_Series_Tutorials_Exercise",
      "es": "https://wiki.seeedstudio.com/es/reComputer_Jetson_Series_Tutorials_Exercise",
      "pt": "https://wiki.seeedstudio.com/pt-br/reComputer_Jetson_Series_Tutorials_Exercise"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "Security Xray Scan Knife Detection",
      "zh": "安全X光扫描刀具检测",
      "ja": "セキュリティX線スキャンナイフ検出",
      "es": "Detección de Cuchillos en Escaneo de Rayos X de Seguridad",
      "pt": "Detecção de Facas em Raio-X de Segurança"
    },
    "img": "https://files.seeedstudio.com/wiki/SecurityCheck/Security_Scan_23.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Security_Scan",
      "zh": "https://wiki.seeedstudio.com/cn/Security_Scan",
      "ja": "https://wiki.seeedstudio.com/ja/Security_Scan",
      "es": "https://wiki.seeedstudio.com/es/Security_Scan",
      "pt": "https://wiki.seeedstudio.com/pt-br/Security_Scan"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "Traffic Management DeepStream SDK",
      "zh": "交通管理 DeepStream SDK",
      "ja": "交通管理 DeepStream SDK",
      "es": "SDK de Gestión de Tráfico DeepStream",
      "pt": "Gerenciamento de Tráfego com DeepStream SDK"
    },
    "img": "https://files.seeedstudio.com/wiki/DeepStream/demo-optimized.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Traffic-Management-DeepStream-SDK",
      "zh": "https://wiki.seeedstudio.com/cn/Traffic-Management-DeepStream-SDK",
      "ja": "https://wiki.seeedstudio.com/ja/Traffic-Management-DeepStream-SDK",
      "es": "https://wiki.seeedstudio.com/es/Traffic-Management-DeepStream-SDK",
      "pt": "https://wiki.seeedstudio.com/pt-br/Traffic-Management-DeepStream-SDK"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "YOLOv11 With Depth Camera on Jetson Orin For Distance Measurement",
      "zh": "在 Jetson Orin 上使用 YOLOv11 与深度相机进行距离测量",
      "ja": "距離測定のためのJetson OrinでのYOLOv11と深度カメラの使用",
      "es": "YOLOv11 Con Cámara de Profundidad en Jetson Orin Para Medición de Distancia",
      "pt": "YOLOv11 com Câmera de Profundidade no Jetson Orin para Medição de Distância"
    },
    "img": "https://files.seeedstudio.com/wiki/Yolo11/connection.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/yolov11_with_depth_camera",
      "zh": "https://wiki.seeedstudio.com/cn/yolov11_with_depth_camera",
      "ja": "https://wiki.seeedstudio.com/ja/yolov11_with_depth_camera",
      "es": "https://wiki.seeedstudio.com/es/yolov11_with_depth_camera",
      "pt": "https://wiki.seeedstudio.com/pt-br/yolov11_with_depth_camera"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "07/04/2025",
    "author": "Zibo"
  },
  {
    "name": {
      "en": "YOLOv26 Dual GMSL Camera Image Processing System on Jetson",
      "zh": "基于 Jetson 的 YOLOv26 双 GMSL 摄像头图像处理系统",
      "ja": "Jetson 上の YOLOv26 デュアル GMSL カメラ画像処理システム",
      "pt": "Sistema de Processamento de Imagens com Câmera Dupla GMSL YOLOv26 no Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/yolov26_on_jetson/local.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/ai_roboticsyolov26_dual_camera_system",
      "zh": "https://wiki.seeedstudio.com/cn/ai_roboticsyolov26_dual_camera_system",
      "ja": "https://wiki.seeedstudio.com/ja/ai_roboticsyolov26_dual_camera_system",
      "pt": "https://wiki.seeedstudio.com/pt-br/ai_roboticsyolov26_dual_camera_system"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "pt": []
    },
    "lastUpdated": "02/10/2026",
    "author": "Lorraine"
  },
  {
    "name": {
      "en": "Getting started with Yolov5 and roboflow",
      "zh": "Yolov5 和 roboflow 入门指南",
      "ja": "YOLOv5とroboflowを始める",
      "es": "Comenzando con Yolov5 y roboflow",
      "pt": "Primeiros passos com Yolov5 e Roboflow"
    },
    "img": "https://files.seeedstudio.com/wiki/YOLOV5/YOLOv5_banner.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/YOLOv5-Object-Detection-Jetson",
      "zh": "https://wiki.seeedstudio.com/cn/YOLOv5-Object-Detection-Jetson",
      "ja": "https://wiki.seeedstudio.com/ja/YOLOv5-Object-Detection-Jetson",
      "es": "https://wiki.seeedstudio.com/es/YOLOv5-Object-Detection-Jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/YOLOv5-Object-Detection-Jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "Deploy YOLOv8 with TensorRT and DeepStream SDK",
      "zh": "使用 TensorRT 和 DeepStream SDK 部署 YOLOv8",
      "ja": "TensorRTとDeepStream SDKを使用したYOLOv8のデプロイ",
      "es": "Desplegar YOLOv8 con TensorRT y DeepStream SDK",
      "pt": "Fazer deploy do YOLOv8 com TensorRT e DeepStream SDK"
    },
    "img": "https://files.seeedstudio.com/wiki/YOLOV8/car.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/YOLOv8-DeepStream-TRT-Jetson",
      "zh": "https://wiki.seeedstudio.com/cn/YOLOv8-DeepStream-TRT-Jetson",
      "ja": "https://wiki.seeedstudio.com/ja/YOLOv8-DeepStream-TRT-Jetson",
      "es": "https://wiki.seeedstudio.com/es/YOLOv8-DeepStream-TRT-Jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/YOLOv8-DeepStream-TRT-Jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "04/21/2023",
    "author": "Lakshantha"
  },
  {
    "name": {
      "en": "Deploy YOLOv8 with TensorRT",
      "zh": "使用 TensorRT 部署 YOLOv8",
      "ja": "TensorRTでYOLOv8をデプロイ",
      "es": "Desplegar YOLOv8 con TensorRT",
      "pt": "Implantar YOLOv8 com TensorRT"
    },
    "img": "https://files.seeedstudio.com/wiki/YOLOV8-TRT/8.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/YOLOv8-TRT-Jetson",
      "zh": "https://wiki.seeedstudio.com/cn/YOLOv8-TRT-Jetson",
      "ja": "https://wiki.seeedstudio.com/ja/YOLOv8-TRT-Jetson",
      "es": "https://wiki.seeedstudio.com/es/YOLOv8-TRT-Jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/YOLOv8-TRT-Jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "07/17/2023",
    "author": "Lakshantha"
  },
  {
    "name": {
      "en": "Train and deploy a custom classification model with YOLOv8",
      "zh": "使用 YOLOv8 训练和部署自定义分类模型",
      "ja": "YOLOv8でカスタム分類モデルを訓練・デプロイする",
      "es": "Entrenar y desplegar un modelo de clasificación personalizado con YOLOv8",
      "pt": "Treine e implemente um modelo de classificação personalizado com YOLOv8"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/reComputer_J4012.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/train_and_deploy_a_custom_classification_model_with_yolov8",
      "zh": "https://wiki.seeedstudio.com/cn/train_and_deploy_a_custom_classification_model_with_yolov8",
      "ja": "https://wiki.seeedstudio.com/ja/train_and_deploy_a_custom_classification_model_with_yolov8",
      "es": "https://wiki.seeedstudio.com/es/train_and_deploy_a_custom_classification_model_with_yolov8",
      "pt": "https://wiki.seeedstudio.com/pt-br/train_and_deploy_a_custom_classification_model_with_yolov8"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "06/11/2024",
    "author": "Bruno"
  },
  {
    "name": {
      "es": "Sistema de Procesamiento de Imágenes con Cámara GMSL Dual YOLOv26 en Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/yolov26_on_jetson/local.png",
    "URL": {
      "es": "https://wiki.seeedstudio.com/es/esai_roboticsyolov26_dual_camera_system"
    },
    "category": {
      "es": []
    },
    "lastUpdated": "02/10/2026",
    "author": "Lorraine"
  }
]

export const communityList_gen = [
  {
    "name": {
      "en": "Control Motor by Voice LLM on Jetson",
      "zh": "在Jetson上通过语音LLM控制电机",
      "ja": "JetsonでのVoice LLMによるモーター制御",
      "es": "Control de Motor por Voz LLM en Jetson",
      "pt": "Controlar Motor por Voz com LLM no Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/voice_control/hardware_connect.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/control_motor_by_voice_llm_on_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/control_motor_by_voice_llm_on_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/control_motor_by_voice_llm_on_jetson",
      "es": "https://wiki.seeedstudio.com/es/control_motor_by_voice_llm_on_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/control_motor_by_voice_llm_on_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "08/19/2025",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Deploy DeepSeek on reComputer Jetson with MLC",
      "zh": "使用MLC在reComputer Jetson上部署DeepSeek",
      "ja": "MLCを使用してreComputer JetsonにDeepSeekをデプロイ",
      "es": "Desplegar DeepSeek en reComputer Jetson con MLC",
      "pt": "Implantar DeepSeek no reComputer Jetson com MLC"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/deepseek/mlc/deploy_deepseek.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/deploy_deepseek_on_jetson_with_mlc",
      "zh": "https://wiki.seeedstudio.com/cn/deploy_deepseek_on_jetson_with_mlc",
      "ja": "https://wiki.seeedstudio.com/ja/deploy_deepseek_on_jetson_with_mlc",
      "es": "https://wiki.seeedstudio.com/es/deploy_deepseek_on_jetson_with_mlc",
      "pt": "https://wiki.seeedstudio.com/pt-br/deploy_deepseek_on_jetson_with_mlc"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "02/13/2025",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Deploy Dia on reComputer Jetson",
      "zh": "在reComputer Jetson上部署Dia",
      "ja": "reComputer JetsonにDiaをデプロイする",
      "es": "Desplegar Dia en reComputer Jetson",
      "pt": "Implantar Dia no reComputer Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/deepseek/mlc/deploy_deepseek.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/deploy_dia_on_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/deploy_dia_on_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/deploy_dia_on_jetson",
      "es": "https://wiki.seeedstudio.com/es/deploy_dia_on_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/deploy_dia_on_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "05/16/2025",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Deploy Live VLM WebUI on reComputer Jetson",
      "zh": "在 reComputer Jetson 上部署 Live VLM WebUI",
      "ja": "reComputer Jetson に Live VLM WebUI をデプロイする",
      "es": "Implementar Live VLM WebUI en reComputer Jetson",
      "pt": "Implantar Live VLM WebUI no reComputer Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/gpt_oss/gptoss-running-live.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/deploy_live_vlm_webui_on_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/deploy_live_vlm_webui_on_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/deploy_live_vlm_webui_on_jetson",
      "es": "https://wiki.seeedstudio.com/es/deploy_live_vlm_webui_on_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/deploy_live_vlm_webui_on_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "12/26/2025",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Local AI Assistant",
      "zh": "本地AI助手",
      "ja": "ローカルAIアシスタント",
      "es": "Asistente de IA Local",
      "pt": "Assistente de IA Local"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/local-ai-assistant/ai-assistant.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/local_ai_ssistant",
      "zh": "https://wiki.seeedstudio.com/cn/local_ai_ssistant",
      "ja": "https://wiki.seeedstudio.com/ja/local_ai_ssistant",
      "es": "https://wiki.seeedstudio.com/es/local_ai_ssistant",
      "pt": "https://wiki.seeedstudio.com/pt-br/local_ai_ssistant"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "07/30/2024",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Local Voice Chatbot",
      "zh": "本地语音聊天机器人",
      "ja": "ローカル音声チャットボット",
      "es": "Chatbot de Voz Local",
      "pt": "Chatbot de Voz Local"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Local_Voice_Chatbot/workflow.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Local_Voice_Chatbot",
      "zh": "https://wiki.seeedstudio.com/cn/Local_Voice_Chatbot",
      "ja": "https://wiki.seeedstudio.com/ja/Local_Voice_Chatbot",
      "es": "https://wiki.seeedstudio.com/es/Local_Voice_Chatbot",
      "pt": "https://wiki.seeedstudio.com/pt-br/Local_Voice_Chatbot"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/14/2024",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Finetune with Llama-Factory",
      "zh": "使用 Llama-Factory 进行微调",
      "ja": "Llama-Factoryでファインチューニング",
      "es": "Ajuste fino con Llama-Factory",
      "pt": "Ajuste fino com Llama-Factory"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/Llama-Factory/run.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Finetune_LLM_on_Jetson",
      "zh": "https://wiki.seeedstudio.com/cn/Finetune_LLM_on_Jetson",
      "ja": "https://wiki.seeedstudio.com/ja/Finetune_LLM_on_Jetson",
      "es": "https://wiki.seeedstudio.com/es/Finetune_LLM_on_Jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/Finetune_LLM_on_Jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "07/03/2024",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Generative AI with reComputer-Jetson®",
      "zh": "使用 reComputer-Jetson® 的生成式 AI",
      "ja": "reComputer-Jetson®による生成AI",
      "es": "IA Generativa con reComputer-Jetson®",
      "pt": "IA Generativa com reComputer-Jetson®"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/deploy-genai-on-jetson.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Generative_AI_Intro",
      "zh": "https://wiki.seeedstudio.com/cn/Generative_AI_Intro",
      "ja": "https://wiki.seeedstudio.com/ja/Generative_AI_Intro",
      "es": "https://wiki.seeedstudio.com/es/Generative_AI_Intro",
      "pt": "https://wiki.seeedstudio.com/pt-br/Generative_AI_Intro"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "08/06/2024",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "GPT-OSS Running Live on reComputer Jetson!",
      "zh": "GPT-OSS在reComputer Jetson上实时运行！",
      "ja": "GPT-OSS Running Live on reComputer Jetson!",
      "es": "¡GPT-OSS Ejecutándose en Vivo en reComputer Jetson!",
      "pt": "GPT-OSS Rodando Ao Vivo no reComputer Jetson!"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/gpt_oss/gptoss-running-live.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/deploy_gptoss_on_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/deploy_gptoss_on_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/deploy_gptoss_on_jetson",
      "es": "https://wiki.seeedstudio.com/es/deploy_gptoss_on_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/deploy_gptoss_on_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "08/14/2025",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Format Output with Langchain",
      "zh": "使用 Langchain 格式化输出",
      "ja": "Langchainで出力をフォーマット",
      "es": "Formatear salida con Langchain",
      "pt": "Formatar saída com Langchain"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Format_LLM_Opt/ai_assistant.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/How_to_Format_the_Output_of_LLM_Using_Langchain_on_Jetson",
      "zh": "https://wiki.seeedstudio.com/cn/How_to_Format_the_Output_of_LLM_Using_Langchain_on_Jetson",
      "ja": "https://wiki.seeedstudio.com/ja/How_to_Format_the_Output_of_LLM_Using_Langchain_on_Jetson",
      "es": "https://wiki.seeedstudio.com/es/How_to_Format_the_Output_of_LLM_Using_Langchain_on_Jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/How_to_Format_the_Output_of_LLM_Using_Langchain_on_Jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "4/1/2024",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Text2Image with Stable Diffusion",
      "zh": "使用 Stable Diffusion 进行文本转图像",
      "ja": "Stable Diffusionを使ったText2Image",
      "es": "Texto a imagen con Stable Diffusion",
      "pt": "Text2Image com Stable Diffusion"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/reComputer_J4012.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/How_to_run_local_llm_text_to_image_on_reComputer",
      "zh": "https://wiki.seeedstudio.com/cn/How_to_run_local_llm_text_to_image_on_reComputer",
      "ja": "https://wiki.seeedstudio.com/ja/How_to_run_local_llm_text_to_image_on_reComputer",
      "es": "https://wiki.seeedstudio.com/es/How_to_run_local_llm_text_to_image_on_reComputer",
      "pt": "https://wiki.seeedstudio.com/pt-br/How_to_run_local_llm_text_to_image_on_reComputer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "04/01/2024",
    "author": "Bruno"
  },
  {
    "name": {
      "en": "How to Run VLM on reComputer",
      "zh": "如何在reComputer上运行VLM",
      "ja": "reComputerでVLMを実行する方法",
      "es": "Cómo Ejecutar VLM en reComputer",
      "pt": "Como Executar VLM no reComputer"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/vlm/vlmgif.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/run_vlm_on_recomputer",
      "zh": "https://wiki.seeedstudio.com/cn/run_vlm_on_recomputer",
      "ja": "https://wiki.seeedstudio.com/ja/run_vlm_on_recomputer",
      "es": "https://wiki.seeedstudio.com/es/run_vlm_on_recomputer",
      "pt": "https://wiki.seeedstudio.com/pt-br/run_vlm_on_recomputer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "7/24/2024",
    "author": "ZhuYaoHui"
  },
  {
    "name": {
      "en": "How to Run Zero-Shot Detection on reComputer",
      "zh": "如何在reComputer上运行零样本检测",
      "ja": "reComputerでZero-Shot Detectionを実行する方法",
      "es": "Cómo Ejecutar Detección Zero-Shot en reComputer",
      "pt": "Como Executar Zero-Shot Detection no reComputer"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/zero_shot_detection/fig1.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/run_zero_shot_detection_on_recomputer",
      "zh": "https://wiki.seeedstudio.com/cn/run_zero_shot_detection_on_recomputer",
      "ja": "https://wiki.seeedstudio.com/ja/run_zero_shot_detection_on_recomputer",
      "es": "https://wiki.seeedstudio.com/es/run_zero_shot_detection_on_recomputer",
      "pt": "https://wiki.seeedstudio.com/pt-br/run_zero_shot_detection_on_recomputer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "7/24/2024",
    "author": "ZhuYaoHui"
  },
  {
    "name": {
      "en": "Local OpenClaw(Clawdbot) on reComputer Jetson with Ollama",
      "zh": "在 reComputer Jetson 上使用 Ollama 运行本地 OpenClaw（Clawdbot）",
      "ja": "reComputer Jetson上でOllamaを使用したローカルOpenClaw（Clawdbot）",
      "es": "OpenClaw(Clawdbot) Local en reComputer Jetson con Ollama",
      "pt": "OpenClaw(Clawdbot) local no reComputer Jetson com Ollama"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/clawdbot/chatops_homepage.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/local_openclaw_on_recomputer_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/local_openclaw_on_recomputer_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/local_openclaw_on_recomputer_jetson",
      "es": "https://wiki.seeedstudio.com/es/local_openclaw_on_recomputer_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/local_openclaw_on_recomputer_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "02/3/2026",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "RAG with LlamaIndex",
      "zh": "使用 LlamaIndex 的 RAG",
      "ja": "LlamaIndexを使用したRAG",
      "es": "RAG con LlamaIndex",
      "pt": "RAG com LlamaIndex"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/RAG-MLC-Jetson.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Local_RAG_based_on_Jetson_with_LlamaIndex",
      "zh": "https://wiki.seeedstudio.com/cn/Local_RAG_based_on_Jetson_with_LlamaIndex",
      "ja": "https://wiki.seeedstudio.com/ja/Local_RAG_based_on_Jetson_with_LlamaIndex",
      "es": "https://wiki.seeedstudio.com/es/Local_RAG_based_on_Jetson_with_LlamaIndex",
      "pt": "https://wiki.seeedstudio.com/pt-br/Local_RAG_based_on_Jetson_with_LlamaIndex"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "05/15/2024",
    "author": "Jiahao"
  },
  {
    "name": {
      "en": "Faster Inference with MLC",
      "zh": "使用 MLC 实现更快推理",
      "ja": "MLC LLMによる高速推論",
      "es": "Inferencia Más Rápida con MLC",
      "pt": "Inferência Mais Rápida com MLC"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/MLC_LLM.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Quantized_Llama2_7B_with_MLC_LLM_on_Jetson",
      "zh": "https://wiki.seeedstudio.com/cn/Quantized_Llama2_7B_with_MLC_LLM_on_Jetson",
      "ja": "https://wiki.seeedstudio.com/ja/Quantized_Llama2_7B_with_MLC_LLM_on_Jetson",
      "es": "https://wiki.seeedstudio.com/es/Quantized_Llama2_7B_with_MLC_LLM_on_Jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/Quantized_Llama2_7B_with_MLC_LLM_on_Jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "04/1/2024",
    "author": "Jiahao"
  },
  {
    "name": {
      "en": "Quickly Deploy DeepSeek on reComputer Jetson",
      "zh": "在reComputer Jetson上快速部署DeepSeek",
      "ja": "reComputer Jetson上でDeepSeekを迅速にデプロイする",
      "es": "Desplegar Rápidamente DeepSeek en reComputer Jetson",
      "pt": "Implante rapidamente o DeepSeek no reComputer Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/deepseek/deepseek.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/deploy_deepseek_on_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/deploy_deepseek_on_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/deploy_deepseek_on_jetson",
      "es": "https://wiki.seeedstudio.com/es/deploy_deepseek_on_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/deploy_deepseek_on_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "02/08/2025",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Real Time Subtitle Recoder",
      "zh": "实时字幕录制器",
      "ja": "リアルタイム字幕レコーダー",
      "es": "Grabador de Subtítulos en Tiempo Real",
      "pt": "Gravador de legendas em tempo real"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/recoder.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Real_Time_Subtitle_Recoder_on_Nvidia_Jetson",
      "zh": "https://wiki.seeedstudio.com/cn/Real_Time_Subtitle_Recoder_on_Nvidia_Jetson",
      "ja": "https://wiki.seeedstudio.com/ja/Real_Time_Subtitle_Recoder_on_Nvidia_Jetson",
      "es": "https://wiki.seeedstudio.com/es/Real_Time_Subtitle_Recoder_on_Nvidia_Jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/Real_Time_Subtitle_Recoder_on_Nvidia_Jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "02/23/2024",
    "author": "Jiahao"
  },
  {
    "name": {
      "en": "Speech2Text with Whisper",
      "zh": "使用 Whisper 进行语音转文本",
      "ja": "Whisper による音声テキスト変換",
      "es": "Voz a Texto con Whisper",
      "pt": "Speech2Text com Whisper"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/Real-Time-Whisper.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Whisper_on_Jetson_for_Real_Time_Speech_to_Text",
      "zh": "https://wiki.seeedstudio.com/cn/Whisper_on_Jetson_for_Real_Time_Speech_to_Text",
      "ja": "https://wiki.seeedstudio.com/ja/Whisper_on_Jetson_for_Real_Time_Speech_to_Text",
      "es": "https://wiki.seeedstudio.com/es/Whisper_on_Jetson_for_Real_Time_Speech_to_Text",
      "pt": "https://wiki.seeedstudio.com/pt-br/Whisper_on_Jetson_for_Real_Time_Speech_to_Text"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "03/14/2024",
    "author": "Jiahao"
  }
]

export const communityList_robot = [

]

export const developerToolsList = [
  {
    "name": {
      "en": "Getting Started with alwaysAI",
      "zh": "alwaysAI 入门指南",
      "ja": "alwaysAIの始め方",
      "es": "Primeros pasos con alwaysAI",
      "pt": "Primeiros Passos com alwaysAI"
    },
    "img": "https://files.seeedstudio.com/wiki/alwaysAI/pics/thumb-5.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/alwaysAI-Jetson-Getting-Started",
      "zh": "https://wiki.seeedstudio.com/cn/alwaysAI-Jetson-Getting-Started",
      "ja": "https://wiki.seeedstudio.com/ja/alwaysAI-Jetson-Getting-Started",
      "es": "https://wiki.seeedstudio.com/es/alwaysAI-Jetson-Getting-Started",
      "pt": "https://wiki.seeedstudio.com/pt-br/alwaysAI-Jetson-Getting-Started"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "1/16/2023",
    "author": "jianjing Huang"
  },
  {
    "name": {
      "en": "Getting Started with Cochl.Sense",
      "zh": "Cochl.Sense 入门指南",
      "ja": "Cochl.Sense の始め方",
      "es": "Primeros pasos con Cochl.Sense",
      "pt": "Primeiros passos com Cochl.Sense"
    },
    "img": "https://files.seeedstudio.com/wiki/Cochl.Sense/1.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Cochl.Sense-Jetson-Getting-Started",
      "zh": "https://wiki.seeedstudio.com/cn/Cochl.Sense-Jetson-Getting-Started",
      "ja": "https://wiki.seeedstudio.com/ja/Cochl.Sense-Jetson-Getting-Started",
      "es": "https://wiki.seeedstudio.com/es/Cochl.Sense-Jetson-Getting-Started",
      "pt": "https://wiki.seeedstudio.com/pt-br/Cochl.Sense-Jetson-Getting-Started"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "03/27/2023",
    "author": "Lakshantha"
  },
  {
    "name": {
      "en": "Getting Started with CVEDIA-RT",
      "zh": "CVEDIA-RT 入门指南",
      "ja": "CVEDIA-RTを始める",
      "es": "Comenzando con CVEDIA-RT",
      "pt": "Primeiros Passos com CVEDIA-RT"
    },
    "img": "https://files.seeedstudio.com/wiki/CVEDIA/thumb.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/CVEDIA-Jetson-Getting-Started",
      "zh": "https://wiki.seeedstudio.com/cn/CVEDIA-Jetson-Getting-Started",
      "ja": "https://wiki.seeedstudio.com/ja/CVEDIA-Jetson-Getting-Started",
      "es": "https://wiki.seeedstudio.com/es/CVEDIA-Jetson-Getting-Started",
      "pt": "https://wiki.seeedstudio.com/pt-br/CVEDIA-Jetson-Getting-Started"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "03/10/2023",
    "author": "Lakshantha"
  },
  {
    "name": {
      "en": "Getting Started with Deci",
      "zh": "Deci 入门指南",
      "ja": "Deci を始める",
      "es": "Primeros pasos con Deci",
      "pt": "Primeiros Passos com Deci"
    },
    "img": "https://files.seeedstudio.com/wiki/DeciAI/Deci-thumb.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/DeciAI-Getting-Started",
      "zh": "https://wiki.seeedstudio.com/cn/DeciAI-Getting-Started",
      "ja": "https://wiki.seeedstudio.com/ja/DeciAI-Getting-Started",
      "es": "https://wiki.seeedstudio.com/es/DeciAI-Getting-Started",
      "pt": "https://wiki.seeedstudio.com/pt-br/DeciAI-Getting-Started"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "Develop reComputer Jetson using Clawdbot",
      "zh": "使用 Clawdbot 开发 reComputer Jetson",
      "ja": "Clawdbotを使用したreComputer Jetsonの開発",
      "es": "Desarrollar reComputer Jetson usando Clawdbot",
      "pt": "Desenvolver reComputer Jetson usando Clawdbot"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/clawdbot/chatops_homepage.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/develop_recomputer_jetson_using_clawdbot",
      "zh": "https://wiki.seeedstudio.com/cn/develop_recomputer_jetson_using_clawdbot",
      "ja": "https://wiki.seeedstudio.com/ja/develop_recomputer_jetson_using_clawdbot",
      "es": "https://wiki.seeedstudio.com/es/develop_recomputer_jetson_using_clawdbot",
      "pt": "https://wiki.seeedstudio.com/pt-br/develop_recomputer_jetson_using_clawdbot"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/28/2026",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Distributed llama.cpp on reComputer Jetson (RPC Mode)",
      "zh": "在 reComputer Jetson 上的分布式 llama.cpp（RPC 模式）",
      "ja": "reComputer Jetson での分散 llama.cpp（RPC モード）",
      "es": "llama.cpp Distribuido en reComputer Jetson (Modo RPC)",
      "pt": "llama.cpp distribuído no reComputer Jetson (Modo RPC)"
    },
    "img": "https://files.seeedstudio.com/wiki/recomputer_robotic_j501/hardware_overview.png.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/ai_robotics_distributed_llama_cpp_rpc_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/ai_robotics_distributed_llama_cpp_rpc_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/ai_robotics_distributed_llama_cpp_rpc_jetson",
      "es": "https://wiki.seeedstudio.com/es/ai_robotics_distributed_llama_cpp_rpc_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/ai_robotics_distributed_llama_cpp_rpc_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "2026-01-09T00:00:00.000Z",
    "author": "Lorraine"
  },
  {
    "name": {
      "en": "Getting Started with Gapi",
      "zh": "Gapi 入门指南",
      "ja": "Gapiの使い始め方",
      "es": "Comenzando con Gapi",
      "pt": "Primeiros Passos com o Gapi"
    },
    "img": "https://genainerds.com/assets/img/GapiGIF.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/gapi_getting_started-with_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/gapi_getting_started-with_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/gapi_getting_started-with_jetson",
      "es": "https://wiki.seeedstudio.com/es/gapi_getting_started-with_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/gapi_getting_started-with_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "09/20/2024",
    "author": "Youjiang"
  },
  {
    "name": {
      "en": "Getting Started with Edge Impulse",
      "zh": "Edge Impulse 入门指南",
      "ja": "Edge Impulseを始める",
      "es": "Comenzando con Edge Impulse",
      "pt": "Primeiros Passos com Edge Impulse"
    },
    "img": "https://files.seeedstudio.com/wiki/2.23jetsonedge/jetsonedge.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/HardHat",
      "zh": "https://wiki.seeedstudio.com/cn/HardHat",
      "ja": "https://wiki.seeedstudio.com/ja/HardHat",
      "es": "https://wiki.seeedstudio.com/es/HardHat",
      "pt": "https://wiki.seeedstudio.com/pt-br/HardHat"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "Bill"
  },
  {
    "name": {
      "en": "Implement Ethercat Communication on reComputer",
      "zh": "在reComputer上实现Ethercat通信",
      "ja": "reComputerでEthercat通信を実装する",
      "es": "Implementar Comunicación Ethercat en reComputer",
      "pt": "Implementar Comunicação Ethercat no reComputer"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/robotics_j401/recomputer-robotics_2.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/recomputer_ethercat_communication",
      "zh": "https://wiki.seeedstudio.com/cn/recomputer_ethercat_communication",
      "ja": "https://wiki.seeedstudio.com/ja/recomputer_ethercat_communication",
      "es": "https://wiki.seeedstudio.com/es/recomputer_ethercat_communication",
      "pt": "https://wiki.seeedstudio.com/pt-br/recomputer_ethercat_communication"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "2025-09-05T00:00:00.000Z",
    "author": "Zibo"
  },
  {
    "name": {
      "en": "Install Pytorch for reComputer Jetson",
      "zh": "为 reComputer Jetson 安装 Pytorch",
      "ja": "reComputer Jetson用PyTorchのインストール",
      "es": "Instalar Pytorch para reComputer Jetson",
      "pt": "Instalar Pytorch para reComputer Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/Yolo11/connection.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/install_torch_on_recomputer",
      "zh": "https://wiki.seeedstudio.com/cn/install_torch_on_recomputer",
      "ja": "https://wiki.seeedstudio.com/ja/install_torch_on_recomputer",
      "es": "https://wiki.seeedstudio.com/es/install_torch_on_recomputer",
      "pt": "https://wiki.seeedstudio.com/pt-br/install_torch_on_recomputer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "07/25/2025",
    "author": "Zibo"
  },
  {
    "name": {
      "en": "Jetson AI Developer Tools",
      "zh": "Jetson AI 开发者工具",
      "ja": "Jetson AI Developer Tools",
      "es": "Herramientas de Desarrollo de IA para Jetson",
      "pt": "Ferramentas de Desenvolvedor Jetson AI"
    },
    "img": "https://files.seeedstudio.com/wiki/recomputerzhongwen/cvedia-logo.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Jetson-AI-developer-tools",
      "zh": "https://wiki.seeedstudio.com/cn/Jetson-AI-developer-tools",
      "ja": "https://wiki.seeedstudio.com/ja/Jetson-AI-developer-tools",
      "es": "https://wiki.seeedstudio.com/es/Jetson-AI-developer-tools",
      "pt": "https://wiki.seeedstudio.com/pt-br/Jetson-AI-developer-tools"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "05/11/2023",
    "author": "Lakshantha"
  },
  {
    "name": {
      "en": "Getting Started with Docker",
      "zh": "Docker 入门指南",
      "ja": "Dockerを始める",
      "es": "Comenzando con Docker",
      "pt": "Primeiros Passos com Docker"
    },
    "img": "https://files.seeedstudio.com/wiki/jetson-docker/1.jpeg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/jetson-docker-getting-started",
      "zh": "https://wiki.seeedstudio.com/cn/jetson-docker-getting-started",
      "ja": "https://wiki.seeedstudio.com/ja/jetson-docker-getting-started",
      "es": "https://wiki.seeedstudio.com/es/jetson-docker-getting-started",
      "pt": "https://wiki.seeedstudio.com/pt-br/jetson-docker-getting-started"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "Use an SPI Display on reComputer J4012 Classic",
      "zh": "在 reComputer J4012 Classic 上使用 SPI 显示屏",
      "ja": "reComputer J4012 Classic で SPI ディスプレイを使用する",
      "es": "Usar una pantalla SPI en reComputer J4012 Classic",
      "pt": "Usar um display SPI no reComputer J4012 Classic"
    },
    "img": "https://files.seeedstudio.com/wiki/Jetson_SPI_Getting_Start/reComputer-J4012-Classic_SPI_picture_02.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/jetson_spi_getting_start",
      "zh": "https://wiki.seeedstudio.com/cn/jetson_spi_getting_start",
      "ja": "https://wiki.seeedstudio.com/ja/jetson_spi_getting_start",
      "es": "https://wiki.seeedstudio.com/es/jetson_spi_getting_start",
      "pt": "https://wiki.seeedstudio.com/pt-br/jetson_spi_getting_start"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "06/01/2026",
    "author": "HaoChen"
  },
  {
    "name": {
      "en": "Getting Started with Lumeo",
      "zh": "Lumeo 入门指南",
      "ja": "Lumeoを始める",
      "es": "Primeros pasos con Lumeo",
      "pt": "Primeiros Passos com Lumeo"
    },
    "img": "https://files.seeedstudio.com/wiki/Lumeo/thumb.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Lumeo-Jetson-Getting-Started",
      "zh": "https://wiki.seeedstudio.com/cn/Lumeo-Jetson-Getting-Started",
      "ja": "https://wiki.seeedstudio.com/ja/Lumeo-Jetson-Getting-Started",
      "es": "https://wiki.seeedstudio.com/es/Lumeo-Jetson-Getting-Started",
      "pt": "https://wiki.seeedstudio.com/pt-br/Lumeo-Jetson-Getting-Started"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "03/10/2023",
    "author": "Lakshantha"
  },
  {
    "name": {
      "en": "No code Edge AI Tool",
      "zh": "无代码边缘AI工具",
      "ja": "ノーコードエッジAIツール",
      "es": "Herramienta de IA Edge sin código",
      "pt": "Ferramenta de Edge AI sem código"
    },
    "img": "https://files.seeedstudio.com/wiki/node-red/step.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/No-code-Edge-AI-Tool",
      "zh": "https://wiki.seeedstudio.com/cn/No-code-Edge-AI-Tool",
      "ja": "https://wiki.seeedstudio.com/ja/No-code-Edge-AI-Tool",
      "es": "https://wiki.seeedstudio.com/es/No-code-Edge-AI-Tool",
      "pt": "https://wiki.seeedstudio.com/pt-br/No-code-Edge-AI-Tool"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "Getting Started with NVStreamer",
      "zh": "NVStreamer入门指南",
      "ja": "NVStreamerの使用開始",
      "es": "Primeros Pasos con NVStreamer",
      "pt": "Primeiros Passos com o NVStreamer"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/recomputerj4012.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/getting_started_with_nvstreamer",
      "zh": "https://wiki.seeedstudio.com/cn/getting_started_with_nvstreamer",
      "ja": "https://wiki.seeedstudio.com/ja/getting_started_with_nvstreamer",
      "es": "https://wiki.seeedstudio.com/es/getting_started_with_nvstreamer",
      "pt": "https://wiki.seeedstudio.com/pt-br/getting_started_with_nvstreamer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "7/24/2024",
    "author": "ZhuYaoHui"
  },
  {
    "name": {
      "en": "Jetson Resource",
      "zh": "Jetson 资源",
      "ja": "Jetson Resource",
      "es": "Recurso Jetson",
      "pt": "Recurso Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/recomputerzhongwen/rewendang.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/reComputer_Jetson_Series_Resource",
      "zh": "https://wiki.seeedstudio.com/cn/reComputer_Jetson_Series_Resource",
      "ja": "https://wiki.seeedstudio.com/ja/reComputer_Jetson_Series_Resource",
      "es": "https://wiki.seeedstudio.com/es/reComputer_Jetson_Series_Resource",
      "pt": "https://wiki.seeedstudio.com/pt-br/reComputer_Jetson_Series_Resource"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/04/2023",
    "author": "w0x7ce"
  },
  {
    "name": {
      "en": "Getting Started with Roboflow",
      "zh": "开始使用 Roboflow",
      "ja": "Roboflow の使用開始",
      "es": "Comenzando con Roboflow",
      "pt": "Primeiros passos com Roboflow"
    },
    "img": "https://files.seeedstudio.com/wiki/Roboflow-inference/9.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Roboflow-Jetson-Getting-Started",
      "zh": "https://wiki.seeedstudio.com/cn/Roboflow-Jetson-Getting-Started",
      "ja": "https://wiki.seeedstudio.com/ja/Roboflow-Jetson-Getting-Started",
      "es": "https://wiki.seeedstudio.com/es/Roboflow-Jetson-Getting-Started",
      "pt": "https://wiki.seeedstudio.com/pt-br/Roboflow-Jetson-Getting-Started"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "10/26/2023",
    "author": "Lakshantha"
  },
  {
    "name": {
      "en": "Using VNC on reComputer Jetson",
      "zh": "在reComputer Jetson上使用VNC",
      "ja": "reComputer JetsonでVNCを使用する",
      "es": "Usando VNC en reComputer Jetson",
      "pt": "Usando VNC no reComputer Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/A608/recomputerj4012.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/vnc_for_recomputer",
      "zh": "https://wiki.seeedstudio.com/cn/vnc_for_recomputer",
      "ja": "https://wiki.seeedstudio.com/ja/vnc_for_recomputer",
      "es": "https://wiki.seeedstudio.com/es/vnc_for_recomputer",
      "pt": "https://wiki.seeedstudio.com/pt-br/vnc_for_recomputer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "9/30/2024",
    "author": "YaoHui Zhu"
  }
]

export const multimodalList = [
  {
    "name": {
      "en": "Local LLM Agent on Jetson for Safe Hardware Interface Control",
      "zh": "Jetson 上的本地 LLM 代理用于安全硬件接口控制",
      "ja": "安全なハードウェアインターフェース制御のためのJetson上のローカルLLMエージェント",
      "es": "Agente LLM Local en Jetson para Control Seguro de Interfaces de Hardware",
      "pt": "Agente LLM Local no Jetson para Controle Seguro de Interfaces de Hardware"
    },
    "img": "https://www.seeedstudio.com/blog/wp-content/uploads/2024/03/image-1030x616.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/llm_interface_control_jetson",
      "zh": "https://wiki.seeedstudio.com/cn/llm_interface_control_jetson",
      "ja": "https://wiki.seeedstudio.com/ja/llm_interface_control_jetson",
      "es": "https://wiki.seeedstudio.com/es/llm_interface_control_jetson",
      "pt": "https://wiki.seeedstudio.com/pt-br/llm_interface_control_jetson"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/29/2025",
    "author": "kourosh"
  },
  {
    "name": {
      "en": "Chatbot on Jetson",
      "zh": "Jetson 上的聊天机器人",
      "ja": "Jetson上のチャットボット",
      "es": "Chatbot en Jetson",
      "pt": "Chatbot no Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Multimodal_ai/local_voice_chatbot/terminal_ollama.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/local_chatbot_recomputer",
      "zh": "https://wiki.seeedstudio.com/cn/local_chatbot_recomputer",
      "ja": "https://wiki.seeedstudio.com/ja/local_chatbot_recomputer",
      "es": "https://wiki.seeedstudio.com/es/local_chatbot_recomputer",
      "pt": "https://wiki.seeedstudio.com/pt-br/local_chatbot_recomputer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/29/2025",
    "author": "kourosh"
  },
  {
    "name": {
      "en": "Deploy local voice LLM on reComputer Mini for Reachy Mini!",
      "zh": "在 reComputer Mini 上为 Reachy Mini 部署本地语音 LLM！",
      "ja": "Reachy Mini用reComputer Miniにローカル音声LLMをデプロイ！",
      "es": "¡Despliega LLM de voz local en reComputer Mini para Reachy Mini!",
      "pt": "Implemente um LLM de voz local no reComputer Mini para o Reachy Mini!"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/reachy_mini/world_frame.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/local_voice_llm_on_recomputer_jetson_for_reachy_mini",
      "zh": "https://wiki.seeedstudio.com/cn/local_voice_llm_on_recomputer_jetson_for_reachy_mini",
      "ja": "https://wiki.seeedstudio.com/ja/local_voice_llm_on_recomputer_jetson_for_reachy_mini",
      "es": "https://wiki.seeedstudio.com/es/local_voice_llm_on_recomputer_jetson_for_reachy_mini",
      "pt": "https://wiki.seeedstudio.com/pt-br/local_voice_llm_on_recomputer_jetson_for_reachy_mini"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/06/2026",
    "author": "youjiang"
  },
  {
    "name": {
      "en": "Run VLM with speech interaction",
      "zh": "运行带语音交互的VLM",
      "ja": "音声インタラクション機能付きVLMの実行",
      "es": "Ejecutar VLM con interacción de voz",
      "pt": "Executar VLM com interação por voz"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Multimodal_ai/audio_vlm/vlmgif.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/speech_vlm",
      "zh": "https://wiki.seeedstudio.com/cn/speech_vlm",
      "ja": "https://wiki.seeedstudio.com/ja/speech_vlm",
      "es": "https://wiki.seeedstudio.com/es/speech_vlm",
      "pt": "https://wiki.seeedstudio.com/pt-br/speech_vlm"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "08/23/2024",
    "author": "YaoHui Zhu"
  },
  {
    "name": {
      "en": "Use Llava to guard your warehouse",
      "zh": "使用 Llava 守护您的仓库",
      "ja": "Llavaを使用して倉庫を守る",
      "es": "Usar Llava para proteger tu almacén",
      "pt": "Use Llava para proteger seu armazém"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Industrial/reComputer-Industrial-J4012.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/vlm",
      "zh": "https://wiki.seeedstudio.com/cn/vlm",
      "ja": "https://wiki.seeedstudio.com/ja/vlm",
      "es": "https://wiki.seeedstudio.com/es/vlm",
      "pt": "https://wiki.seeedstudio.com/pt-br/vlm"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "10/10/2025",
    "author": "Jiahao Li"
  }
]

export const physicalAIList = [
  {
    "name": {
      "en": "Control Rebot Arm with NemoClaw on Nvidia Jetson Thor",
      "zh": "在 Nvidia Jetson Thor 上使用 NemoClaw 控制 reBot Arm",
      "ja": "Nvidia Jetson Thor 上の NemoClaw で reBot Arm を制御する",
      "es": "Controlar reBot Arm con NemoClaw en Nvidia Jetson Thor",
      "pt": "Controlar o reBot Arm com NemoClaw no Nvidia Jetson Thor"
    },
    "img": "https://media-cdn.seeedstudio.com/media/catalog/product/cache/bb49d3ec4ee05b6f018e93f896b8a25d/i/m/img_v3_0210p_67d75fe6-a1fe-40a9-b025-ac92efb1bbbg_1.jpg",
    "URL": {
      "en": "https://wiki.seeedstudio.com/control_rebot_arm_with_nemoclaw_on_nvidia_jetson_thor",
      "zh": "https://wiki.seeedstudio.com/cn/control_rebot_arm_with_nemoclaw_on_nvidia_jetson_thor",
      "ja": "https://wiki.seeedstudio.com/ja/control_rebot_arm_with_nemoclaw_on_nvidia_jetson_thor",
      "es": "https://wiki.seeedstudio.com/es/control_rebot_arm_with_nemoclaw_on_nvidia_jetson_thor",
      "pt": "https://wiki.seeedstudio.com/pt-br/control_rebot_arm_with_nemoclaw_on_nvidia_jetson_thor"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "05/18/2026",
    "author": "youjiang"
  },
  {
    "name": {
      "en": "Control SO-Arm by OpenClaw on Jetson Thor",
      "zh": "在 Jetson Thor 上通过 OpenClaw 控制 SO-Arm",
      "ja": "Jetson Thor上でOpenClawによりSO-Armを制御する",
      "es": "Controlar SO-Arm con OpenClaw en Jetson Thor",
      "pt": "Controlar SO-Arm com OpenClaw no Jetson Thor"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/openclaw/soarm_claw.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/ai_robotics_control_soarm_by_openclaw_on_jetson_thor",
      "zh": "https://wiki.seeedstudio.com/cn/ai_robotics_control_soarm_by_openclaw_on_jetson_thor",
      "ja": "https://wiki.seeedstudio.com/ja/ai_robotics_control_soarm_by_openclaw_on_jetson_thor",
      "es": "https://wiki.seeedstudio.com/es/ai_robotics_control_soarm_by_openclaw_on_jetson_thor",
      "pt": "https://wiki.seeedstudio.com/pt-br/ai_robotics_control_soarm_by_openclaw_on_jetson_thor"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "03/09/2026",
    "author": "youjiang"
  },
  {
    "name": {
      "en": "Fine-tune Isaac GR00T N1.5 for LeRobot SO-101 Arm and Deploy on Jetson Thor",
      "zh": "为 LeRobot SO-101 机械臂微调 Isaac GR00T N1.5 并在 Jetson Thor 上部署",
      "ja": "LeRobot SO-101 アーム用 Isaac GR00T N1.5 のファインチューニングと Jetson Thor へのデプロイ",
      "es": "Ajustar Isaac GR00T N1.5 para el Brazo LeRobot SO-101 y Desplegar en Jetson Thor",
      "pt": "Ajustar Fino o Isaac GR00T N1.5 para o Braço LeRobot SO-101 e Implantar no Jetson Thor"
    },
    "img": "https://files.seeedstudio.com/wiki/other/cover1.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/fine_tune_gr00t_n1.5_for_lerobot_so_arm_and_deploy_on_jetson_thor_bk",
      "zh": "https://wiki.seeedstudio.com/cn/fine_tune_gr00t_n1.5_for_lerobot_so_arm_and_deploy_on_jetson_thor_bk",
      "ja": "https://wiki.seeedstudio.com/ja/fine_tune_gr00t_n1.5_for_lerobot_so_arm_and_deploy_on_jetson_thor_bk",
      "es": "https://wiki.seeedstudio.com/es/fine_tune_gr00t_n1.5_for_lerobot_so_arm_and_deploy_on_jetson_thor_bk",
      "pt": "https://wiki.seeedstudio.com/pt-br/fine_tune_gr00t_n1.5_for_lerobot_so_arm_and_deploy_on_jetson_thor_bk"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "2025-9-11",
    "author": "AI&Robotics Group"
  },
  {
    "name": {
      "en": "Fine-tune Isaac GR00T N1.6 for LeRobot SO-101 Arm and Deploy on AGX Orin",
      "zh": "为 LeRobot SO-101 机械臂微调 Isaac GR00T N1.6 并在 AGX Orin 上部署",
      "ja": "LeRobot SO-101 アーム用 Isaac GR00T N1.6 のファインチューニングと AGX Orin でのデプロイ",
      "es": "Ajustar Isaac GR00T N1.6 para el Brazo LeRobot SO-101 y Desplegar en AGX Orin",
      "pt": "Ajustar Finamente Isaac GR00T N1.6 para o Braço LeRobot SO-101 e Implantar no AGX Orin"
    },
    "img": "https://files.seeedstudio.com/wiki/other/cover1.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/fine_tune_gr00t_n1.6_for_lerobot_so_arm_and_deploy_on_agx_orin",
      "zh": "https://wiki.seeedstudio.com/cn/fine_tune_gr00t_n1.6_for_lerobot_so_arm_and_deploy_on_agx_orin",
      "ja": "https://wiki.seeedstudio.com/ja/fine_tune_gr00t_n1.6_for_lerobot_so_arm_and_deploy_on_agx_orin",
      "es": "https://wiki.seeedstudio.com/es/fine_tune_gr00t_n1.6_for_lerobot_so_arm_and_deploy_on_agx_orin",
      "pt": "https://wiki.seeedstudio.com/pt-br/fine_tune_gr00t_n1.6_for_lerobot_so_arm_and_deploy_on_agx_orin"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "2026-1-6",
    "author": "Dayu"
  },
  {
    "name": {
      "en": "Getting Started with Jetson-Claw on Orin Nano / NX 8GB",
      "zh": "在 Orin Nano / NX 8GB 上快速上手 Jetson-Claw",
      "ja": "Orin Nano / NX 8GB での Jetson-Claw 入門",
      "es": "Introducción a Jetson-Claw en Orin Nano / NX 8GB",
      "pt": "Introdução ao Jetson-Claw no Orin Nano / NX 8GB"
    },
    "img": "https://files.seeedstudio.com/wiki/jetson/jetson-claw-fornt.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/getting_started_with_jetson_claw_on_orin_nano_nx_8gb",
      "zh": "https://wiki.seeedstudio.com/cn/getting_started_with_jetson_claw_on_orin_nano_nx_8gb",
      "ja": "https://wiki.seeedstudio.com/ja/getting_started_with_jetson_claw_on_orin_nano_nx_8gb",
      "es": "https://wiki.seeedstudio.com/es/getting_started_with_jetson_claw_on_orin_nano_nx_8gb",
      "pt": "https://wiki.seeedstudio.com/pt-br/getting_started_with_jetson_claw_on_orin_nano_nx_8gb"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "03/26/2026",
    "author": "Dayu"
  },
  {
    "name": {
      "en": "Fruit Sorting with J501 Mini and StarAI Viola Arm",
      "zh": "使用 J501 Mini 和 StarAI Viola 机械臂进行水果分拣",
      "ja": "J501 MiniとStarAI Violaアームによるフルーツ仕分け",
      "es": "Clasificación de Frutas con J501 Mini y Brazo StarAI Viola",
      "pt": "Classificação de Frutas com J501 Mini e Braço StarAI Viola"
    },
    "img": "https://files.seeedstudio.com/wiki/other/j501mini-startai-front.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/j501_mini_starai_viola_fruit_sorting",
      "zh": "https://wiki.seeedstudio.com/cn/j501_mini_starai_viola_fruit_sorting",
      "ja": "https://wiki.seeedstudio.com/ja/j501_mini_starai_viola_fruit_sorting",
      "es": "https://wiki.seeedstudio.com/es/j501_mini_starai_viola_fruit_sorting",
      "pt": "https://wiki.seeedstudio.com/pt-br/j501_mini_starai_viola_fruit_sorting"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "2026-2-2",
    "author": "Dayu"
  },
  {
    "name": {
      "en": "Chatbot on Jetson",
      "zh": "Jetson 上的聊天机器人",
      "ja": "Jetson上のチャットボット",
      "es": "Chatbot en Jetson",
      "pt": "Chatbot no Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer/Application/Multimodal_ai/local_voice_chatbot/terminal_ollama.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/local_chatbot_recomputer_bk",
      "zh": "https://wiki.seeedstudio.com/cn/local_chatbot_recomputer_bk",
      "ja": "https://wiki.seeedstudio.com/ja/local_chatbot_recomputer_bk",
      "es": "https://wiki.seeedstudio.com/es/local_chatbot_recomputer_bk",
      "pt": "https://wiki.seeedstudio.com/pt-br/local_chatbot_recomputer_bk"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/29/2025",
    "author": "kourosh"
  },
  {
    "name": {
      "en": "Deploy local voice LLM on reComputer Mini for Reachy Mini!",
      "zh": "在 reComputer Mini 上为 Reachy Mini 部署本地语音 LLM！",
      "ja": "Reachy Mini用reComputer Miniにローカル音声LLMをデプロイ！",
      "es": "¡Despliega LLM de voz local en reComputer Mini para Reachy Mini!",
      "pt": "Implante um LLM de voz local no reComputer Mini para o Reachy Mini!"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/reachy_mini/world_frame.webp",
    "URL": {
      "en": "https://wiki.seeedstudio.com/local_voice_llm_on_recomputer_jetson_for_reachy_mini_bk",
      "zh": "https://wiki.seeedstudio.com/cn/local_voice_llm_on_recomputer_jetson_for_reachy_mini_bk",
      "ja": "https://wiki.seeedstudio.com/ja/local_voice_llm_on_recomputer_jetson_for_reachy_mini_bk",
      "es": "https://wiki.seeedstudio.com/es/local_voice_llm_on_recomputer_jetson_for_reachy_mini_bk",
      "pt": "https://wiki.seeedstudio.com/pt-br/local_voice_llm_on_recomputer_jetson_for_reachy_mini_bk"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "01/06/2026",
    "author": "youjiang"
  },
  {
    "name": {
      "en": "Control Multiple Reachy Mini Robots with a Fleet Dance Console on Jetson",
      "zh": "在 Jetson 上通过集群舞蹈控制台控制多台 Reachy Mini 机器人",
      "ja": "Jetson 上のフリートダンスコンソールで複数の Reachy Mini ロボットを制御する",
      "es": "Controla múltiples robots Reachy Mini con una consola de baile de flota en Jetson",
      "pt": "Controle vários robôs Reachy Mini com um console de dança de frota no Jetson"
    },
    "img": "https://files.seeedstudio.com/wiki/reComputer-Jetson/reachy_mini/world_frame.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/ai_robotics_reachy_fleet_dance",
      "zh": "https://wiki.seeedstudio.com/cn/ai_robotics_reachy_fleet_dance",
      "ja": "https://wiki.seeedstudio.com/ja/ai_robotics_reachy_fleet_dance",
      "es": "https://wiki.seeedstudio.com/es/ai_robotics_reachy_fleet_dance",
      "pt": "https://wiki.seeedstudio.com/pt-br/ai_robotics_reachy_fleet_dance"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "03/25/2026",
    "author": "Youjiang"
  }
]

export const managedServicesList = [
  {
    "name": {
      "en": "Getting Started with Allxon",
      "zh": "Allxon 入门指南",
      "ja": "Allxon の使用開始",
      "es": "Primeros Pasos con Allxon",
      "pt": "Primeiros Passos com Allxon"
    },
    "img": "https://www.allxon.com/hs-fs/hubfs/Allxon_%E6%8F%92%E7%95%AB_20210512-+NVIDIA.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Allxon-Jetson-Getting-Started",
      "zh": "https://wiki.seeedstudio.com/cn/Allxon-Jetson-Getting-Started",
      "ja": "https://wiki.seeedstudio.com/ja/Allxon-Jetson-Getting-Started",
      "es": "https://wiki.seeedstudio.com/es/Allxon-Jetson-Getting-Started",
      "pt": "https://wiki.seeedstudio.com/pt-br/Allxon-Jetson-Getting-Started"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "1/13/2023",
    "author": "jianjing Huang"
  },
  {
    "name": {
      "en": "Getting started of NEQTO Engine for Linux on reComputer J30",
      "zh": "在 reComputer J30 上开始使用 NEQTO Engine for Linux",
      "ja": "reComputer J30 での NEQTO Engine for Linux の開始方法",
      "es": "Introducción a NEQTO Engine para Linux en reComputer J30",
      "pt": "Primeiros passos com o NEQTO Engine para Linux no reComputer J30"
    },
    "img": "https://files.seeedstudio.com/wiki/wiki-ranger/Contributions/neqto_engine_for_linux_recomputer/header-img_2x.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/neqto_engine_for_linux_recomputer",
      "zh": "https://wiki.seeedstudio.com/cn/neqto_engine_for_linux_recomputer",
      "ja": "https://wiki.seeedstudio.com/ja/neqto_engine_for_linux_recomputer",
      "es": "https://wiki.seeedstudio.com/es/neqto_engine_for_linux_recomputer",
      "pt": "https://wiki.seeedstudio.com/pt-br/neqto_engine_for_linux_recomputer"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "03/14/2024",
    "author": "Kazuhiro Ozuchi"
  },
  {
    "name": {
      "en": "Getting Started with Scailable",
      "zh": "Scailable 入门指南",
      "ja": "Scailable を始める",
      "es": "Primeros pasos con Scailable",
      "pt": "Primeiros passos com Scailable"
    },
    "img": "https://files.seeedstudio.com/wiki/Scailable/wiki-thumb-4.gif",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Scailable-Jetson-Getting-Started",
      "zh": "https://wiki.seeedstudio.com/cn/Scailable-Jetson-Getting-Started",
      "ja": "https://wiki.seeedstudio.com/ja/Scailable-Jetson-Getting-Started",
      "es": "https://wiki.seeedstudio.com/es/Scailable-Jetson-Getting-Started",
      "pt": "https://wiki.seeedstudio.com/pt-br/Scailable-Jetson-Getting-Started"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "03/10/2023",
    "author": "Lakshantha"
  },
  {
    "name": {
      "en": "OTA Update NVIDIA Jetson Using Allxon",
      "zh": "使用 Allxon 进行 NVIDIA Jetson OTA 更新",
      "ja": "AllxonでNVIDIA JetsonをOTA更新する",
      "es": "Actualización OTA de NVIDIA Jetson usando Allxon",
      "pt": "Atualizar NVIDIA Jetson por OTA usando Allxon"
    },
    "img": "https://files.seeedstudio.com/wiki/Allxon/JetPack-OTA/thumb.png",
    "URL": {
      "en": "https://wiki.seeedstudio.com/Update-Jetson-Linux-OTA-Using-Allxon",
      "zh": "https://wiki.seeedstudio.com/cn/Update-Jetson-Linux-OTA-Using-Allxon",
      "ja": "https://wiki.seeedstudio.com/ja/Update-Jetson-Linux-OTA-Using-Allxon",
      "es": "https://wiki.seeedstudio.com/es/Update-Jetson-Linux-OTA-Using-Allxon",
      "pt": "https://wiki.seeedstudio.com/pt-br/Update-Jetson-Linux-OTA-Using-Allxon"
    },
    "category": {
      "en": [],
      "zh": [],
      "ja": [],
      "es": [],
      "pt": []
    },
    "lastUpdated": "1/13/2023",
    "author": "jianjing Huang"
  }
]

