position: 5 # float position is supported
label: '5. Deploy & Maintain'
collapsible: true # make the category collapsible
collapsed: true # keep the category collapsed by default
className: recamera_pro_deploy
