import type {ReactNode} from 'react';
import type {Locale} from '../../pages/home/lib/locale';

const SHOPPING_BAG = 'Bazaar \u{1F6CD}\uFE0F';

// Navbar 标签翻译字典，仅覆盖出现频率较高的导航项
const NAV_LABEL_I18N: Record<Locale, Record<string, string>> = {
  en: {
    'Quick Links': 'Quick Links',
    'Explore with Topics': 'Explore with Topics',
    FAQs: 'FAQs',
    'Get Involved': 'Get Involved',
    'Sensor and Sensing': 'Sensor and Sensing',
    Networking: 'Networking',
    'Edge Computing': 'Edge Computing',
    Cloud: 'Cloud',
    Solutions: 'Solutions',
    Discord: 'Discord',
    Forum: 'Forum',
    TinyML: 'TinyML',
    'SenseCraft Model Assistant': 'SenseCraft Model Assistant',
    'Home Assistant': 'Home Assistant',
    'Open Source': 'Open Source',
    'Edge AI': 'Edge AI',
    'NVIDIA Jetson Series': 'NVIDIA Jetson Series',
    'Seeed Studio XIAO Series': 'Seeed Studio XIAO Series',
    'reComputer R1000 Series': 'reComputer R1000 Series',
    reTerminal: 'reTerminal',
    reRouter: 'reRouter',
    Odyssey: 'Odyssey',
    'Wio Terminal': 'Wio Terminal',
    Email: 'Email',
    'Have Suggestions?': 'Have Suggestions?',
    'Affiliate & Creator': 'Affiliate & Creator',
    Rangers: 'Rangers',
    Contributors: 'Contributors',
    'Apply for Rangers': 'Apply for Rangers',
    'Direct to Assignments': 'Direct to Assignments',
    'More about Rangers': 'More about Rangers',
    'More about Contributors': 'More about Contributors',
    [SHOPPING_BAG]: SHOPPING_BAG,
    Bazaar: 'Bazaar',
    'SenseCraft AI': 'SenseCraft AI',
    'Getting Started': 'Getting Started',
    Network: 'Network',
    'Project Hub': 'Project Hub',
    Partners: 'Partners',
    Distributors: 'Distributors',
    'How to get help': 'How to get help',
    'Technical Support': 'Technical Support',
    'About Seeed': 'About Seeed',
    'Join us': 'Join us',
    'Contact Us': 'Contact Us',
    Press: 'Press',
  },
  cn: {
    'Quick Links': '快速入口',
    'Explore with Topics': '按主题探索',
    FAQs: '常见问题',
    'Get Involved': '参与我们',
    'Sensor and Sensing': '传感器与感知',
    Networking: '网络',
    'Edge Computing': '边缘计算',
    Cloud: '云',
    Solutions: '解决方案',
    Discord: 'Discord 社区',
    Forum: '论坛',
    TinyML: 'TinyML',
    'SenseCraft Model Assistant': 'SenseCraft 模型助手',
    'Home Assistant': 'Home Assistant',
    'Open Source': '开源',
    'Edge AI': '边缘 AI',
    'NVIDIA Jetson Series': 'NVIDIA Jetson 系列',
    'Seeed Studio XIAO Series': 'Seeed Studio XIAO 系列',
    'reComputer R1000 Series': 'reComputer R1000 系列',
    reTerminal: 'reTerminal',
    reRouter: 'reRouter',
    Odyssey: 'Odyssey',
    'Wio Terminal': 'Wio Terminal',
    Email: '邮箱',
    'Have Suggestions?': '意见反馈',
    'Affiliate & Creator': '联盟与创作者',
    Rangers: '社区大使计划',
    Contributors: '贡献者',
    'Apply for Rangers': '申请成为社区大使',
    'Direct to Assignments': '前往任务看板',
    'More about Rangers': '关于社区大使',
    'More about Contributors': '关于贡献者',
    [SHOPPING_BAG]: '商店 \u{1F6CD}\uFE0F',
    Bazaar: '商店',
    'SenseCraft AI': 'SenseCraft AI',
    'Getting Started': '快速开始',
    Network: '网络',
    'Project Hub': '项目中心',
    Partners: '合作伙伴',
    Distributors: '分销商',
    'How to get help': '如何获得帮助',
    'Technical Support': '技术支持',
    'About Seeed': '关于 Seeed',
    'Join us': '加入我们',
    'Contact Us': '联系我们',
    Press: '媒体报道',
  },
  ja: {
    'Quick Links': 'クイックリンク',
    'Explore with Topics': 'トピックで探す',
    FAQs: 'よくある質問',
    'Get Involved': '参加する',
    'Sensor and Sensing': 'センサーとセンシング',
    Networking: 'ネットワーキング',
    'Edge Computing': 'エッジコンピューティング',
    Cloud: 'クラウド',
    Solutions: 'ソリューション',
    Discord: 'Discord',
    Forum: 'フォーラム',
    TinyML: 'TinyML',
    'SenseCraft Model Assistant': 'SenseCraft モデルアシスタント',
    'Home Assistant': 'Home Assistant',
    'Open Source': 'オープンソース',
    'Edge AI': 'エッジAI',
    'NVIDIA Jetson Series': 'NVIDIA Jetson シリーズ',
    'Seeed Studio XIAO Series': 'Seeed Studio XIAO シリーズ',
    'reComputer R1000 Series': 'reComputer R1000 シリーズ',
    reTerminal: 'reTerminal',
    reRouter: 'reRouter',
    Odyssey: 'Odyssey',
    'Wio Terminal': 'Wio Terminal',
    Email: 'メール',
    'Have Suggestions?': 'ご意見はありますか？',
    'Affiliate & Creator': 'アフィリエイト & クリエイター',
    Rangers: 'コミュニティアンバサダー',
    Contributors: 'コントリビューター',
    'Apply for Rangers': 'コミュニティアンバサダーへの応募',
    'Direct to Assignments': '課題ボードへ',
    'More about Rangers': 'コミュニティアンバサダーの詳細',
    'More about Contributors': 'コントリビューターの詳細',
    [SHOPPING_BAG]: 'ストア \u{1F6CD}\uFE0F',
    Bazaar: 'バザール',
    'SenseCraft AI': 'SenseCraft AI',
    'Getting Started': 'はじめに',
    Network: 'ネットワーク',
    'Project Hub': 'プロジェクトハブ',
    Partners: 'パートナー',
    Distributors: 'ディストリビューター',
    'How to get help': 'ヘルプの受け方',
    'Technical Support': '技術サポート',
    'About Seeed': 'Seeed について',
    'Join us': '採用情報',
    'Contact Us': 'お問い合わせ',
    Press: 'プレス',
  },
  es: {
    'Quick Links': 'Enlaces rápidos',
    'Explore with Topics': 'Explorar por temas',
    FAQs: 'Preguntas frecuentes',
    'Get Involved': 'Participa',
    'Sensor and Sensing': 'Sensores y sensado',
    Networking: 'Redes',
    'Edge Computing': 'Computación perimetral',
    Cloud: 'Nube',
    Solutions: 'Soluciones',
    Discord: 'Discord',
    Forum: 'Foro',
    TinyML: 'TinyML',
    'SenseCraft Model Assistant': 'Asistente de modelos SenseCraft',
    'Home Assistant': 'Home Assistant',
    'Open Source': 'Código abierto',
    'Edge AI': 'IA de borde',
    'NVIDIA Jetson Series': 'Serie NVIDIA Jetson',
    'Seeed Studio XIAO Series': 'Serie Seeed Studio XIAO',
    'reComputer R1000 Series': 'Serie reComputer R1000',
    reTerminal: 'reTerminal',
    reRouter: 'reRouter',
    Odyssey: 'Odyssey',
    'Wio Terminal': 'Wio Terminal',
    Email: 'Correo electrónico',
    'Have Suggestions?': '¿Tienes sugerencias?',
    'Affiliate & Creator': 'Afiliados y Creadores',
    Rangers: 'Embajador/a de la comunidad',
    Contributors: 'Colaboradores',
    'Apply for Rangers': 'Solicitar Embajador/a de la comunidad',
    'Direct to Assignments': 'Ir a las tareas',
    'More about Rangers': 'Más sobre los Embajador/a de la comunidad',
    'More about Contributors': 'Más sobre los colaboradores',
    [SHOPPING_BAG]: 'Tienda \u{1F6CD}\uFE0F',
    Bazaar: 'Tienda',
    'SenseCraft AI': 'SenseCraft AI',
    'Getting Started': 'Primeros pasos',
    Network: 'Red',
    'Project Hub': 'Centro de proyectos',
    Partners: 'Socios',
    Distributors: 'Distribuidores',
    'How to get help': 'Cómo obtener ayuda',
    'Technical Support': 'Soporte técnico',
    'About Seeed': 'Acerca de Seeed',
    'Join us': 'Únete a nosotros',
    'Contact Us': 'Contáctanos',
    Press: 'Prensa',
  },
};

export function translateNavbarLabel(
  label: ReactNode,
  locale: Locale
): ReactNode {
  if (typeof label !== 'string') return label;
  const dict = NAV_LABEL_I18N[locale];
  if (!dict) return label;
  if (label in dict) return dict[label];
  if (label === 'Bazaar 🛍️') {
    return dict[SHOPPING_BAG] ?? label;
  }
  return label;
}
