name: Check_PR

on:
   schedule:
    #UTC 0 
    - cron: '0 0 10 3 *'
      

jobs:
  lint:
    name: test_ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Checkout
        uses: actions/checkout@master
        
#       - name: INSTALL SSH KEY
#         uses: shimataro/ssh-key-action@v2
#         with:
#           key: ${{ secrets.SECRETS_SSH_PC }} 
#           known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
#       - name: Adding Known Hosts
#         run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
#       - name: Deploy with rsync
#         run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/wait-to-fill/

      - name: GIT CLONE
        run: |
            sudo apt-get update
            sudo apt-get install \
                  git -y 
            git config --global user.name 'tianrking'
            git config --global user.email 'tian.r.king@gmail.com'
            git clone git@github.com:Seeed-Studio/wiki-documents.git ~/wiki-documents
            
      - name: NPM RUN for HTML BUILD
        run: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            cd  ~/wiki-documents
            sudo apt remove cmdtest
            sudo apt update && sudo apt install yarn
            yarn
            yarn build
      






          
